### ISSUE TITLE
audio desync

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/libopenshot#115]
So, yesterday, I found this issue in OpenShot. I was editing 30fps footages and I was trying to have the clips sync up to the audio (music, actually) [like the awesome Edgar Wright does](https://www.youtube.com/watch?v=6XMuUVw7TOM), so masterfully. But when I rendered it out to check it (because the preview isn't always the very best in OpenShot - see #114), the clips that seemed to be so in-sync with the music in the preview was out of sync. I was using the right profile (720p @ 30fps) to edit and render the footage. So, I decided to do a test. And this is how it went:

I created a new project (HDV 720 24p) and imported an mp3 file. I also went ahead and created a title that read 'OpenShot Test' and keyframed it to scale with the pulse of the music. [The preview looked fine](https://youtu.be/qEFqt61q61s), however [the render was a tad bit out-of-sync](https://youtu.be/81rf-HOg7T0). I even tried rendering to [other profiles](https://youtu.be/poSZgqEHb-8). It is still a tad bit out of sync.
If you clap along with the pulse of the music, you'll see that in the preview one, the scaling-s are in sync with the pulse of the music whereas in  the renders, it is a bit off.
This is just a guinea test, however. In my real project, the de-sync was a lot more perceivable.

I am not quite sure what is causing this. But this does need to be fixed. Esp. so as I am exporting in the same profile that I created the video in...

I am attaching the `.osp` project file and the `.mp3` file just in case someone wants to test this out for themselves.
[OpenShot audio-keyframe-sync test.tar.gz](https://github.com/OpenShot/libopenshot/files/2097527/OpenShot.audio-keyframe-sync.test.tar.gz)
[Silicon_Transmitter_-_01_-_Murmuration.mp3.tar.gz](https://github.com/OpenShot/libopenshot/files/2097531/Silicon_Transmitter_-_01_-_Murmuration.mp3.tar.gz)

**Comment by jeffski** [comment]
I've noticed some strange things happening with the timing too. For example if I try and render just an image clip and try and write a video 2 seconds long at 24fps - I'd expect a video that is 2 seconds long with 48 frames - I actually get 28 frames. If I use a clip that is 2 seconds long but write out a video totaling 10 seconds (240 frames) then the actual image clip part is now 48 frames but the total video is 220 frames (would expect 240). This is all just in done in C++ using the library, not in the editor software. I'll try and post up some code examples and videos to help explain. Not sure if this is the same issue.

**Comment by jeffski** [comment]
I have filed a new issue with some a code sample: https://github.com/OpenShot/libopenshot/issues/122. Be great @peanutbutterandcrackers if you could test that and see if you have the same issue.

**Comment by peanutbutterandcrackers** [comment]
@jeffski - Sorry for the delay in my reply. I was trying to compile it but couldn't. How does it work, again? I'm sorry. I am only good with Python stuff (and not so very good at that, either). In the meantime, I have found another issue that I will be reporting soon which is possibly related to these two. Most definitely.
