### ISSUE TITLE
'Blur' Bug

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/libopenshot#116]
Last night, I found a bug in the blur effect. The `vertical radius` parameter does not respect manually set values over saves. It is reverting back to `6` every time the project is re-opened (after saving).

In the following screenshot, I set the `vertical radius` value to `0` in the very first frame and save the project (note the save indicator).
![screenshot at 2018-06-14 07-33-10](https://user-images.githubusercontent.com/26764547/41387408-7f28b30e-6fa6-11e8-84d7-e68ab97a22b4.png)
Now, after re-opening the project, this is what I see (again, note the save indicator):
![screenshot at 2018-06-14 07-33-38](https://user-images.githubusercontent.com/26764547/41387452-a3035e3c-6fa6-11e8-87d6-540920fed1b4.png)
The `vertical radius` value has reverted back to `6`. [Oops. Sorry I just realized my OpenShot UI is using Devanagari numerals. But that `६` thingy means `6'.

Also, It's the same if I keyframe the property in the middle of the clip. Here are two screen-shots showing the same thing, again:
![screenshot at 2018-06-14 07-41-36](https://user-images.githubusercontent.com/26764547/41387535-1d743902-6fa7-11e8-978b-8fecf4a85669.png)
![screenshot at 2018-06-14 07-41-58](https://user-images.githubusercontent.com/26764547/41387536-1e5a9636-6fa7-11e8-816c-5564bc526d45.png)
[Reverting back to `६`/`6`, again]

Additional Info: If I set the `vertical radius` to any value, during the session, it works just fine, in the previews - at least. If I export it, however, even during the same session, the exported video seems to have a motion blur rather than Gaussian blur - so the `vertical radius` value is being ignored even during export within the same session.

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - Perhaps you'd have some ideas regarding this, good sir?

**Comment by N3WWN** [comment]
@peanutbutterandcrackers - Please prepare for a PR to the develop branch momentarily! 😉

**Comment by N3WWN** [comment]
Why?!  Oh why is this failing?  There is no reason it should be failing.  I thought it was because I branched from the master instead of develop branch and then set the PR for the develop branch (PR 117), so I deleted that branch and rebranched from the develop branch and made the same changes and submitted PR 118, but that's failing, too.  It compiles just fine on my end.  I really don't know what to do in order to get PRs to work.

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - Agh. That is just sad. Perhaps we should have some way to know *why* the builds are failing... Doesn't look like it should cause a build failure, though.

**Comment by N3WWN** [comment]
@peanutbutterandcrackers - Exactly.  It builds just fine on my dev system (not even a warning, let alone an error) and there's no preprocessor directives (i.e. macros or defines) that could be failing on one build system versus another.  

The original PR #117 was out of date, which is why I closed it and submitted PR #118 fresh after making sure the changed files were based on the current (at the time) develop branch.

**Comment by peanutbutterandcrackers** [comment]
PR #118 is *currently* out of date with the base branch, though. It says so right now. Perhaps you'd like to update it, kind sir? Maybe then it'll pass the build tests?

**Comment by N3WWN** [comment]
There must be some change with how github shows PRs now... PR #118 is one commit behind develop and one commit ahead of develop, with no conflicts.  This is to be expected with PRs that are not merged before another change is committed to the branch.

At any rate, I've clicked the "Update Branch" button and checks are running again.

**Comment by N3WWN** [comment]
Luckily, all checks passed this time even though nothing changed whatsoever. 🍀 I'm buying a lottery ticket! 😜

**Comment by peanutbutterandcrackers** [comment]
Maybe there really are ghosts in the machine. lol :smile:

**Comment by ferdnyc** [comment]
Re: Build failures...

> Perhaps we should have some way to know why the builds are failing... Doesn't look like it should cause a build failure, though.

That's the thing that I find perplexing: why the BuildKite details for builds of [lib]openshot[-audio][-qt] are behind a login. This isn't an issue I've encountered with any other CI systems. When I submitted, e.g., my html-lint PR petdance/html-lint#66 and TravisCI performed its build, I was able to click on [Details](https://travis-ci.org/petdance/html-lint/builds/390378076?utm_source=github_status) to view the _entire_ set of build logs, for all 9 builds, which means if any of them had failed I'd have been able to see exactly what the issues were.

My mindset, from the bad old days of centralized VC, is that breaking the build is a Big Deal™, and whenever anyone is guilty of such a sin the onus is on them to fix it. I realize that the whole point of CI systems building every _proposed_ change is to catch problems **before** they get committed and actually do break the build, making failures far less of a Big Deal™. But old habits die hard, and when I see that red × I still feel personally responsible for making it go away. Except, with BuildKite, I'm not able to see any of the relevant information I would need to effectively do that.

I'd be a huge help for those of us submitting PRs, if we could get some sort of clue _why_ BuildKite is all pissed off. (Which sometimes feels like its natural state.) Right now it feels like [the inkjet printer of build systems](https://www.youtube.com/watch?v=pQGtucrJ8hM).

...Or, barring that, if it didn't display the link right there next to the failure message, taunting us with inaccessible information. (Though, that may be GitHub assuming that checks will be accessible.)

**Comment by N3WWN** [comment]
@ferdnyc Thank you for voicing this in a concise and coherent manner.  I don't think that's something I could have done. 😉 

I totally feel responsible for :x:s when they show up as part of one of my PRs, but not knowing what broke or why doesn't leave me with any recourse to fix what I done broke. 😿

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc @N3WWN - Mr. Thomas is now quite done with his work on the build system and perhaps he will soon arrange for the logs to be seen by anyone. I have also dropped him a reminder about this, again. Hope that's comforting. :)
