### ISSUE TITLE
How to compile lib open shot using Visual studio?

### ISSUE THREAD

**Issue by DavidXanatos** [OpenShot/libopenshot#12]
How to compile lib open shot using Visual studio?

I tried that and I end up with a lib but the example.exe rashes :(

**Comment by ferdnyc** [comment]
Currently only GNU compilers are officially supported, on Windows we build with `g++` from the MSYS2 / MinGW 64 projects. It's possible someone's managed to build with the Visual Studio tools, but they'd need a full set of the dependencies built the same way, which is a tall order all by itself.
