### ISSUE TITLE
Enable build with system jsoncpp

### ISSUE THREAD

**Issue by ghisvail** [OpenShot/libopenshot#14]
The Debian packaging policy discourages using embedded dependencies for building binary packages. Right now, libopenshot compiles unconditionally with an embedded copy of `jsoncpp`, which is a breach of this policy.

It would be desirable to allow for (optional ?) compilation and linkage with a system installed `jsoncpp`, such as the one available with the `libjsoncpp-dev` package in Debian / Ubuntu.

**Comment by komackaj** [comment]
+1
Building libopenshot prerequisites multiple libraries, IMHO jsoncpp should be one of it.
But there might be problems with version - I wasn't able to detect the embedded one. I've tried to use system jsoncpp for compilation on Debian Jessie, but there are compilation errors claiming ambigous overload both with 0.6.0 and 1.6.5, so maybe some code changes will be needed.

If @jonoomph approves, after deciding which major version to use, I may try to make an PR for this.

**Comment by ghisvail** [comment]
@komackaj So what you are saying is that you tried a build with `libjsoncpp-dev` from `jessie` (0.6.0) and `jessie-backports` (1.6.5) and it failed for both?

**Comment by komackaj** [comment]
@ghisvail yes, but I've already located the source of error, fix it an managed to build for both major versions - no versions problem anymore.
Last question standing is, whether to prefer system version packages / custom builds via cmake options and throw the thirdparty folder away (would be my choice) or keep possibility of embedding (and how).

**Comment by ghisvail** [comment]
@komackaj I would suggest keeping the embedded copy of `libjsoncpp` and have a `USE_SYSTEM_JSONCPP` cmake option defaulting to `OFF` which would conditionally switch to finding a system installed version. That way the default build workflow would remain unchanged for @jonoomph.

**Comment by ghisvail** [comment]
This is the patch I intended to implement for the Debian packaging, but I would happily take yours @komackaj if you come up with something @jonoomph is happy with.

**Comment by komackaj** [comment]
Made some progress - almost ready in https://github.com/komackaj/libopenshot/commit/36af4edc23f2adf37e26e54edbb993ff0068dde4 
This compiles but linking targets fails with `make[2]: *** No rule to make target  „jsoncpp_lib-NOTFOUND“ needed by"src/libopenshot.so.0.1.0".  Stop.` I am quite new to CMake's `find_package` in config mode, so maybe this is some trivial error - I would appreciate any pointings towards solving this.

Looking at `jsoncppConfig.cmake` content I should just use target `jsoncpp_lib` in `target_link_libraries`, if I understand that right. It has `INTERFACE_INCLUDE_DIRECTORIES` property set correctly, so headers got found. But
- I don't understand why it tries to build it, when `jsoncpp_lib` is defined as `IMPORTED`
- I can't see is any `IMPORTED_LOCATION` property or `LIBRARIES` variable set, or any other way to obtain additional LDFLAGS to bypass the problem.

Replacing the line 163 in referred commit with
```
get_target_property(JSONCPP_INCLUDE_DIR jsoncpp_lib INTERFACE_INCLUDE_DIRECTORIES)
include_directories(${JSONCPP_INCLUDE_DIR})
SET(JSONCPP_LIBRARIES "jsoncpp")
```
makes the compilation work, but I'm sure that's not the way to do it.

Finally I just want to point out that `jsoncppConfig.cmake` is distributed in Debian only with `libjsoncpp-dev` 1.6.5, not 0.6.0, so this will work only from `stretch` on or with `jessie-backports`, but I think it is enough.

**Comment by ghisvail** [comment]
@komackaj Thanks for your progress on this.

> I would appreciate any pointings towards solving this.

I will provide some clues in the comment section of your commit. You are not that far off.

> Finally I just want to point out that jsoncppConfig.cmake is distributed in Debian only with libjsoncpp-dev 1.6.5, not 0.6.0, so this will work only from stretch on or with jessie-backports, but I think it is enough.

New packages are supposed to target `unstable` anyway. Since a potential backport would have to be distributed via `jessie-backports` and `jsoncpp` is at the right version there, then it is not an issue.

**Comment by jonoomph** [comment]
Please let me know when you have a patch ready, and I'll be happy to take a look and merge this into libopenshot. Thanks for the help!
