### ISSUE TITLE
Unable to find "effects/Bars.h"

### ISSUE THREAD

**Issue by v1993** [OpenShot/libopenshot#153]
I want to write application with your library. I use CMake as build system. After adding a lot of finders I got stuck at this error:

        [1/2] Building CXX object CMakeFiles/reverse-easy.dir/src/main.cpp.o
    FAILED: CMakeFiles/reverse-easy.dir/src/main.cpp.o
    /usr/bin/c++  -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -I/usr/include/libopenshot -I/usr/include/libopenshot-audio -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/libavformat -I/usr/include/x86_64-linux-gnu/libavcodec -I/usr/include/x86_64-linux-gnu/libavutil -I/usr/include/x86_64-linux-gnu/libswscale -I/usr/include/jsoncpp -fPIC -MD -MT CMakeFiles/reverse-easy.dir/src/main.cpp.o -MF CMakeFiles/reverse-easy.dir/src/main.cpp.o.d -o CMakeFiles/reverse-easy.dir/src/main.cpp.o -c ../src/main.cpp
    In file included from /usr/include/libopenshot/Clip.h:45:0,
                     from /usr/include/libopenshot/OpenShot.h:106,
                     from ../src/main.cpp:2:
    /usr/include/libopenshot/Effects.h:32:10: fatal error: effects/Bars.h: No such file or directory
     #include "effects/Bars.h"
              ^~~~~~~~~~~~~~~~
    compilation terminated.
    ninja: build stopped: subcommand failed.
Now I'm completely confused: not only compiler, but even `locate` or `apt-find` can't find this file.

What can I do to fix it? I use stable PPA.

**Comment by v1993** [comment]
After copying `include` from upstream everything works, but there is something very wrong with PPA headers.

**Comment by ferdnyc** [comment]
This most likely would've been fixed by the changes from @RichiCoder1 and @jeffski in PR #101, which were merged August 8. If the build you were working with was made before that commit (likely), the install process was putting the effects headers in the wrong place.
