### ISSUE TITLE
Error when using time mapping

### ISSUE THREAD

**Issue by v1993** [OpenShot/libopenshot#155]
I try to use `Clip` with time like this:

    clip->time = Keyframe();
	clip->time.AddPoint(1.0, len);
	clip->time.AddPoint(len, 1.0);
Where `len` is video length.
But get SIGSEGV on random place of `GetFrame` (always new frame number on each run).

Stacktrace by eclipse:

    reverse-easy [17337] [cores: 0,2,3]
        Thread #1 [reverse-easy] 17337 [core: 0] (Suspended : Signal : SIGSEGV:Segmentation fault)
                __memmove_avx_unaligned_erms() at memmove-vec-unaligned-erms.S:484 0x7ffff2b84db1
                juce::AudioSampleBuffer::setSize() at 0x7ffff26e17d3
                openshot::AudioResampler::SetBuffer() at 0x7ffff7acf101
                openshot::Clip::get_time_mapped_frame() at 0x7ffff7aedd33
                openshot::Clip::GetFrame() at 0x7ffff7aecb41
                main() at main.cpp:146 0x40b6a0
        Thread #2 [ZMQbg/0] 17347 [core: 0] (Suspended : Container)
                epoll_wait() at epoll_wait.c:30 0x7ffff2b17bb7
                0x7ffff1ec6781
                0x7ffff1f05554
                start_thread() at pthread_create.c:463 0x7ffff2dee6db
                clone() at clone.S:95 0x7ffff2b1788f
        Thread #3 [ZMQbg/1] 17348 [core: 3] (Suspended : Container)
                epoll_wait() at epoll_wait.c:30 0x7ffff2b17bb7
                0x7ffff1ec6781
                0x7ffff1f05554
                start_thread() at pthread_create.c:463 0x7ffff2dee6db
                clone() at clone.S:95 0x7ffff2b1788f
        Thread #4 [reverse-easy] 17351 [core: 2] (Suspended : Container)
                futex_abstimed_wait_cancelable() at futex-internal.h:205 0x7ffff2df76d6
                do_futex_wait() at sem_waitcommon.c:111 0x7ffff2df76d6
                __new_sem_wait_slow() at sem_waitcommon.c:181 0x7ffff2df77c8
                0x7fffed4aa281
                start_thread() at pthread_create.c:463 0x7ffff2dee6db
                clone() at clone.S:95 0x7ffff2b1788f
        Thread #5 [reverse-easy] 17352 [core: 3] (Suspended : Container)
                futex_abstimed_wait_cancelable() at futex-internal.h:205 0x7ffff2df76d6
                do_futex_wait() at sem_waitcommon.c:111 0x7ffff2df76d6
                __new_sem_wait_slow() at sem_waitcommon.c:181 0x7ffff2df77c8
                0x7fffed4aa281
                start_thread() at pthread_create.c:463 0x7ffff2dee6db
                clone() at clone.S:95 0x7ffff2b1788f
        Thread #6 [reverse-easy] 17353 [core: 0] (Suspended : Container)
                futex_abstimed_wait_cancelable() at futex-internal.h:205 0x7ffff2df76d6
                do_futex_wait() at sem_waitcommon.c:111 0x7ffff2df76d6
                __new_sem_wait_slow() at sem_waitcommon.c:181 0x7ffff2df77c8
                0x7fffed4aa281
                start_thread() at pthread_create.c:463 0x7ffff2dee6db
                clone() at clone.S:95 0x7ffff2b1788f
        Thread #7 [reverse-easy] 17354 [core: 0] (Suspended : Container)
                futex_abstimed_wait_cancelable() at futex-internal.h:205 0x7ffff2df76d6
                do_futex_wait() at sem_waitcommon.c:111 0x7ffff2df76d6
                __new_sem_wait_slow() at sem_waitcommon.c:181 0x7ffff2df77c8
                0x7fffed4aa1c8
                start_thread() at pthread_create.c:463 0x7ffff2dee6db
                clone() at clone.S:95 0x7ffff2b1788f
        Thread #8 [reverse-easy] 17355 [core: 3] (Suspended : Container)
                sched_yield() at syscall-template.S:78 0x7ffff2af9e57
                0x7ffff326edcb
                0x7ffff3270dc7
                0x7ffff3252ac4
                0x7ffff3292418
                start_thread() at pthread_create.c:463 0x7ffff2dee6db
                clone() at clone.S:95 0x7ffff2b1788f
        Thread #9 [reverse-easy] 17356 [core: 3] (Suspended : Container)
                0x7ffff326ed6f
                0x7ffff3270dc7
                0x7ffff3252ac4
                0x7ffff3292418
                start_thread() at pthread_create.c:463 0x7ffff2dee6db
                clone() at clone.S:95 0x7ffff2b1788f
        Thread #10 [reverse-easy] 17357 [core: 2] (Suspended : Container)
                0x7ffff326ed6f
                0x7ffff3270dc7
                0x7ffff3252ac4
                0x7ffff3292418
                start_thread() at pthread_create.c:463 0x7ffff2dee6db
                clone() at clone.S:95 0x7ffff2b1788f
Am I doing something wrong or is it real issue?

**Comment by peanutbutterandcrackers** [comment]
I might be extremely mistaken, but I wonder if this is related to #176 ? Just in case someone wants to help the user out
