### ISSUE TITLE
Incorrect lib folder

### ISSUE THREAD

**Issue by fduraibi** [OpenShot/libopenshot#16]
Installing the library (and the audio library) under fedora 64bit (also redhat, centos and other distros that follow such standard) incorrectly places the libraries under: `/usr/local/lib` which is the place for 32bit libraries, while 64bit libraries should go to `/usr/local/lib64`

Another minor issue which is even after moving the libraries to the correct folder I still get an error when running `openshot-qt`:

```
logger:ERROR libopenshot.so.7: cannot open shared object file: No such file or directory
```

I believe it is not looking for the libraries inside `/usr/local/lib64` and only searching in `/usr/lib64`

To fix that i ran:
    export LD_LIBRARY_PATH=/usr/local/lib64/
before running `openshot-qt`, so I am not sure of this is normal or the install process should handle this!

**Comment by ferdnyc** [comment]
This is, fortunately, fixed with the introduction of `GNUInstallDirs` to the CMake build. (Unfortunately, the Python bindings are still being placed in the wrong `site-packages` folder, but that's being worked on in #290.
