### ISSUE TITLE
Make tests and unittest++ optional

### ISSUE THREAD

**Issue by sbraz** [OpenShot/libopenshot#17]
Hi,
Would it be possible to make the dependency on unittest++ optional? I am pretty sure it is only needed by developers who run tests.

**Comment by RussNelson** [comment]
It should only be required by openshot_test, which oughtn't to be included in the distribution.

**Comment by sbraz** [comment]
On a related note, `DISABLE_TESTS` does not entirely disable tests. I think the whole `tests` directory should be skipped if it's enabled.
