### ISSUE TITLE
Error linking libopenshot.dll while compiling on Windows

### ISSUE THREAD

**Issue by beuz502** [OpenShot/libopenshot#190]
Make gets stuck at 76% "Linking cxx shared library libopenshot.dll" and I get a bunch of undefined references like this:
CacheDisk.cpp:50: undefined reference to '__imp__ZN4QDirC1ERK7QString'

**Comment by beuz502** [comment]
I think it's not linking against Qt, but I don't know why, since it correctly finds the Qt path... should I use an older version?

**Comment by beuz502** [comment]
That might be it, I'm getting "no relevant classes found".

**Comment by darshitvvora** [comment]
@beuz502 - Did you figure out solution? I am getting same errors while compiling on windows? Can you provide exact steps for compiling on windows 10 64bit?

**Comment by ferdnyc** [comment]
"No relevant classes" is not an error, it's normal and expected output — not all of the MOC'd files contain meta-object code, and Qt handles that automatically. It's merely noting that fact during the course of its operation.

If you're getting build failures that are causing `make` to abort, please:

1. Delete your build directory and create a new, empty one
1. Re-run the CMake command you used to set it up.
1. After the build environment is generated, run the make command with the argument `VERBOSE=1` to capture the commands from each step of the build.
1. Post the **ENTIRE** output from start to finish, including both the CMake and make commands and all of their output. (You can save it in a .txt file and upload it as a comment attachment.)

**Comment by beuz502** [comment]
> 
> 
> @beuz502 - Did you figure out solution? I am getting same errors while compiling on windows? Can you provide exact steps for compiling on windows 10 64bit?

It took me quite a while just get to this point. Most of the errors were related to Qt classes, which led me to use an older version of qt. I don't think I had any success, since I ended up giving up on using the lib. Sorry.

**Comment by aditya10avg** [comment]
[error in libopenshot.docx](https://github.com/user-attachments/files/16436411/error.in.libopenshot.docx)
I have attached my commands and errors I received while building it . Help me solve the issue .
