### ISSUE TITLE
Can't access project files directly

### ISSUE THREAD

**Issue by Deathmun** [OpenShot/libopenshot#195]
I cannot simply double-click the project and open it. I need to open a new instance of OpenShot, File > Recent Projects in order to access things I was working on. When I do try to open it normally I get the following error:
![openshot bug](https://user-images.githubusercontent.com/41401014/53305334-73a04a80-384e-11e9-830f-cadc6b51ec01.png)

**Comment by ferdnyc** [comment]
I believe this was my argument-passing bug, fixed in OpenShot/openshot-qt#2355.
