### ISSUE TITLE
Clip speed up and slow down

### ISSUE THREAD

**Issue by djsimonage** [OpenShot/libopenshot#200]
I would like to report a bug when you first speed up the clip 4x and then you see it goes to fast and want to slow down the clip by 2x.
This should result in the clip being sped up by 2x. Instead the length of the clip is right but it is 2x slower than the original, so you lose part of your clip.
I don't know is this is already fixed.
This is my first time usage and I just want to help with improving the program.

**Comment by sjorspeterse** [comment]
I have this issue as well

**Comment by ggigabyte** [comment]
Me too!
