### ISSUE TITLE
Default build is in debug mode

### ISSUE THREAD

**Issue by schauveau** [OpenShot/libopenshot#201]
The file src/CMakeLists.txt is explicitly adding `-g -ggdb` to CMAKE_CXX_FLAGS which means that the library is built in debug mode. That implies -O0 (no optimisation) when no other `-O` options are specified. This happens when building the library as described in the installation manual. This is also how he official Debian package is currently built (and probably other other linux distributions). This is not cool because some parts of the library are quite slow when they are not compiled in optimized mode (e.g. Frame::AddMagickImage ). 

With CMake, the proper way to select the optimization level is by setting the CMAKE_BUILD_TYPE variable to Debug, Release, or RelWithDebInfo (optimized but with debug information)

```
cd build ; cmake -DCMAKE_BUILD_TYPE=Debug .. 
```

If the default flags are not good enough then they can be customized for each build type by setting variables such CMAKE_CXX_FLAGS_DEBUG or CMAKE_CXX_FLAGS_RELEASE in CMakeList.txt. 

So my advice is
- remove `-g -ggdb` from CMakeList.txt
- document CMAKE_BUILD_TYPE in the Installation Manual 

It should be noted that the default build type in cmake is 'None' which is not necessarily a good default since no optimization options are passed to the compiler. It could be a good idea to set the default built mode to Release.

**Comment by ferdnyc** [comment]
For the record (and in support of this suggestion, basically), we're currently doing the following in the rpmfusion (Fedora) RPM spec:

```spec
sed -e 's|-g -ggdb|-g|g' -i src/CMakeLists.txt tests/CMakeLists.txt
sed -e 's|-std=c++11|%{optflags} -std=c++11 %{__global_ldflags} -Wl,--as-needed|g' -i CMakeLists.txt
```
```spec
%cmake3 -Wno-dev -DCMAKE_BUILD_TYPE:STRING=Release \
 -DCMAKE_SKIP_RPATH:BOOL=YES -DUSE_SYSTEM_JSONCPP:BOOL=ON .
```

(The `%{optflags}` will insert `-O2`, and as the `gcc` man page notes, "GCC allows you to use `-g` with `-O`." So that's why we leave the `-g`.)

**Comment by SuslikV** [comment]
So, why it isn't resolved yet? Are there any disadvantages from making debug optional? The change wouldn't be too complex, I think.

**Comment by SuslikV** [comment]
Was solved by merging the https://github.com/OpenShot/libopenshot/pull/334

**Comment by ferdnyc** [comment]
Indeed, thanks @SuslikV . Closing.
