### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ekner** [OpenShot/libopenshot#22]
Very nice and detailed documentation in InstallationGuide.pdf!

However, under "Build & Install OpenShot Video Library (libopenshot) on Linux ", it stands that you should run "python" in order to test the python bindings. This will by default start python 2.7, and when I typed "import openshot" I directly got errors, so apparently the API is only compatible with python 3. Perhaps it should stand python3 instead of python.

**Comment by jonoomph** [comment]
Thanks for the catch. I've corrected the document, and checked in the newest PDF into the libopenshot/doc folder. Thanks!
