### ISSUE TITLE
WebAssembly port?

### ISSUE THREAD

**Issue by NicklausBrain** [OpenShot/libopenshot#221]
Is it possible to make libopenshot compiled into web assembly?
How complex is that task?
I am sure that such possibility would extremely expand the adoption of this library all over the world.

**Comment by jonoomph** [comment]
That is a great question! I don't know enough about web assemblies to make an informed comment though. But if it's possible to include native C/C++, and supports dynamic linking, and such, it is probably possible (in theory). However, how fast would it be? How stable? All good questions.

**Comment by halfanko** [comment]
great question iam cuurently searching about this

**Comment by SaadBazaz** [comment]
Following!
It's super interesting and can take OpenShot to another frontier.
