### ISSUE TITLE
Mouse wheel is under-used

### ISSUE THREAD

**Issue by RussNelson** [OpenShot/libopenshot#25]
Scrolling is difficult. There are three things to be scrolled:
- The time magnifier (which changes the width of the clips window)
- The clips window (which changes the location of the window horizontally)
- The tracks (which changes the location of the window vertically)
- And then there's the location of the cursor.

I know that there are reliability concerns which are _much_ more important than anything in the user interface (who cares how well it works, when it doesn't work at all?) Still, I wanted to get my ideas written down so that other people can take potshots at them. Here's how I think it should work. I'm going to assume that there is no point in allowing the cursor to go out of the clips window[1]
- The cursor should _always_ be visible. If it gets moved out of the clips window, the clips window should move to include it.
- If the mouse wheel runs while the mouse cursor is pointing at the timeline, it should move the cursor, which will also scroll the clips window.
- If the mouse wheel runs while the mouse cursor is pointing at the timeline magnifier, it should (does) zoom in and out on the timeline, but the cursor goes off screen. It shouldn't.
- If the mouse wheel runs while the mouse cursor is pointing at the HH:MM:SS:hh display, it should increment or decrement the time, which of course means moving the time cursor which may mean scrolling the clips window.

[1] I may be wrong about that. When you're playing back the video, it may be too time-consuming to also scroll the clips window at the same time as playing the video. But that would just mean delaying the clips window scroll. As soon as you stopped, the cursor would come back into view.
Also, it may be that there is some value to looking somewhere other than the cursor in the clips window. But you'd think that you could just drop a marker, go look elsewhere, and then go back to the marker. Maybe this is my lack of experience in using openshot?

**Comment by ferdnyc** [comment]
Very belatedly closing this as an issue for the openshot-qt project, not libopenshot.
