### ISSUE TITLE
Example programs in python which are using libopenshot library

### ISSUE THREAD

**Issue by manu51188** [OpenShot/libopenshot#261]
Hi Team,

I am looking for some example programs in python using libopenshot library. I searched online, but didn't found any.

Can anyone help me sharing the python program examples on how to use libopenshot library ?

Thanks and Regards,
Mohit

**Comment by SuslikV** [comment]
This is the worst decision you can make (by using libopenshot for your needs). But well known example is here: https://github.com/OpenShot/openshot-qt

**Comment by ferdnyc** [comment]
> I am looking for some example programs in python using libopenshot library. I searched online, but didn't found any.
> 
> Can anyone help me sharing the python program examples on how to use libopenshot library ?

As @SuslikV says, the OpenShot application is, in a sense, a big example libopenshot-python program. But for a more concise example of how the libopenshot Python API is used, the [`src/examples/Openshot Wipe Tests.py`](https://github.com/OpenShot/libopenshot/blob/develop/src/examples/OpenShot%20Wipe%20Tests.py) program (in this repository) covers the very basics... though it could be commented better.

**Comment by ferdnyc** [comment]
Closing as hopefully answered? Let us know if you have any more questions.

**Comment by veilm** [comment]
Sorry for the 6y-later necropost but any clarification on why using libopenshot is the worst decision you can make (if it still is)?

I was considering using it for programmatic video editing - I have some effects and transitions and overlays in mind, and would only need my program to swap out some metadata like the font and the source video filepaths
