### ISSUE TITLE
CharReader* reader need delete

### ISSUE THREAD

**Issue by laochen** [OpenShot/libopenshot#271]
Upgrade jsoncpp to 1.8.4 , all readers need delete
	
        Json::CharReader* reader(rbuilder.newCharReader());
	string errors;
	bool success = reader->parse( value.c_str(), 
                 value.c_str() + value.size(), &root, &errors );
         delete reader;   // this line

**Comment by ferdnyc** [comment]
@laochen Quite right, thanks! How embarrassing.

Coincidentally, just yesterday I'd been running `valgrind` on the test executable (`tests/openshot-test`) to test for leaks, and hadn't even looked at the results yet. Sure enough, all of the JSON functions were registering memory leaks from the un-deleted `reader` objects.

They were only a couple of Kb each, max, and in fact eliminating _all_ of them only reduced the leaked memory size reported by valgrind from 95.5 Kb to 89.6 Kb. Nevertheless, it's not just about the memory, it's also about writing correct code, and with the `reader`s all being properly freed now, there isn't a single instance of any `Json` function showing up in the `valgrind` output anymore, which of course is the goal!

I've filed #271 to impose discipline upon myself. Many thanks.
