### ISSUE TITLE
Building on linux and porting it for windows?

### ISSUE THREAD

**Issue by cminghao** [OpenShot/libopenshot#279]
Hi, I would like to know if it is possible to build the whole application on Ubuntu for the Windows OS?

**Comment by SuslikV** [comment]
The process is known as cross-platform compilation or just cross-compiling. Widely used for Android applications, for example. Probably, you'll become first who will do it to libopenshot.

**Comment by ferdnyc** [comment]
Possible? In _theory_, yes, for libopenshot. It uses nothing but cross-platform POSIX-compliant libraries that should be available for other platforms. In fact, even when it's running on Windows the MinGW environment is **effectively** using gcc as a cross-compiler for Win32 and Win64 objects.

Fedora has a fairly extensive MinGW setup that I've toyed with trying the same thing in, but haven't gotten around to it yet.

It's definitely never been done yet, though (at least to my knowledge), so whether it's possible in practical terms... or more to the point, whether it WORKS if built that way... is an unanswered question.

**Comment by cminghao** [comment]
ok, thank you for the clarifications!
