### ISSUE TITLE
libavformat missing on compilation.. but its there

### ISSUE THREAD

**Issue by Askmewho** [OpenShot/libopenshot#291]
Note: I am on rpi3... its just for educational porpoise , I wont make any openshot project on it (but yes on rpi4!!)
Note 2: This its a masterpiece software. thanks to make it open source.

It could be than its broken somehow or its not the required version??

I will compile master ffmpeg...

```
pi@raspberrypi:~/Desktop/openshot_dependencies/libopenshot/build $ sudo apt install libavformat-dev
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
libavformat-dev ya está en su versión más reciente (7:4.1.3-1+rpt1).
El paquete indicado a continuación se instaló de forma automática y ya no es necesario.
  rpi.gpio-common
Utilice «sudo apt autoremove» para eliminarlo.
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
pi@raspberrypi:~/Desktop/openshot_dependencies/libopenshot/build $ cmake ../
-----------------------------------------------------------------
          Welcome to the OpenShot Build System!

CMake will now check libopenshot's build dependencies and inform
you of any missing files or other issues.

For more information, please visit <http://www.openshot.org/>.
-----------------------------------------------------------------

Generating build files for OpenShot
  Building libopenshot (version 0.2.3)
  SO/API/ABI Version: 17

CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find FFmpeg (missing: AVFORMAT_LIBRARIES AVFORMAT_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindFFmpeg.cmake:161 (find_package_handle_standard_args)
  src/CMakeLists.txt:83 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/pi/Desktop/openshot_dependencies/libopenshot/build/CMakeFiles/CMakeOutput.log".
```

**Comment by ferdnyc** [comment]
@Askmewho 

Version 4.1.3 should be fine, I use 4.1.4 and libopenshot works with any 3.x - 4.x.

The problem may be a path issue. CMake doesn't have FFmpeg support built in, so we use our own Find module. It may not support the paths on RPi, though that should be an easy fix.

It's **POSSIBLE** the issue is that one of the other required libs is missing, and it's only reporting `AVFORMAT_LIBRARIES` mistakenly. I would also try the following:
```sh
# These are the other two required components
sudo apt install libavcodec-dev libavutil-dev 

# These will also be used, although it shouldn't fail if they're not present
sudo apt install libavdevice-dev libavfilter-dev libswresample-dev libswscale-dev libavresample-dev
```

If that doesn't solve the issue, can you please try the following commands?
```sh
# $LIBOPENSHOT_REPO_PATH is wherever you cloned the repo
cd $LIBOPENSHOT_REPO_PATH

# This will check for FFmpeg the same way CMakeLists.txt does, if it fails please post
# the output
cmake -DCMAKE_MODULE_PATH=cmake/Modules --find-package -DNAME=FFmpeg \
-DCOMPILER_ID=GNU -DLANGUAGE=C -DMODE=LINK

# The output of the that command on my Fedora 30 system is:
# /lib64/libavcodec.so /lib64/libavformat.so /lib64/libavutil.so 

# Assuming the previous command failed with an error, please also run:
cmake -DCMAKE_MODULE_PATH=cmake/Modules --find-package -DNAME=FFmpeg \
-DCOMPILER_ID=GNU -DLANGUAGE=C -DMODE=LINK --trace
```

The output from the last command will be very long, so it would be best to attach it as a text file.

**Comment by Askmewho** [comment]
yeah, it detects ffmpeg now. Ive deleted the build directory and remake it. invoking cmake from now it detects it. weird thing. many thanks!! i will close it for now! 

now I am facing problems with the audio library (didnt know than it has to be compiled first :) ) 
but I am pretty sure its related to this crappy gcc 8.x from the repo.
```
Scanning dependencies of target openshot-audio-test-sound
[ 88%] Building CXX object src/CMakeFiles/openshot-audio-test-sound.dir/Main.cpp.o
[100%] Linking CXX executable openshot-audio-test-sound
/usr/bin/ld: ../libopenshot-audio.so.0.1.8: referencia a `__atomic_load_8' sin definir
/usr/bin/ld: ../libopenshot-audio.so.0.1.8: referencia a `__atomic_store_8' sin definir
/usr/bin/ld: ../libopenshot-audio.so.0.1.8: referencia a `__atomic_fetch_add_8' sin definir
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/openshot-audio-test-sound.dir/build.make:87: src/openshot-audio-test-sound] Error 1
make[1]: *** [CMakeFiles/Makefile2:160: src/CMakeFiles/openshot-audio-test-sound.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by ferdnyc** [comment]
I hope so, it's also _possible_ that JUCE (the audio library libopenshot-audio is built on) uses instructions that aren't supported on the RPi. I don't know if anyone's ever tried building it there, to be honest. I'll see if I can dig up any info.

**Comment by ferdnyc** [comment]
[This info](https://github.com/rec/echomesh/blob/master/documentation/Building%20Juce%20applications%20on%20the%20Raspberry%20Pi.md) says it works. That info is also a few _years_ old, and the JUCE code has changed greatly since. So, not definitive. But there is hope.

**Comment by Askmewho** [comment]
I will solve it! let me research! it will be wonderful on rpi4 ( aside very long rendering times hahhaa) . this gcc has retrocomptibility targets, maybe arm6 (from rpi 1) didnt support it and thats why its throwing that error

**Comment by ferdnyc** [comment]
Here are a couple of [resources](https://mhamilt.github.io/blog/2018/10/23/JUCE-on-Pi.html) that are a bit [more current](https://forum.juce.com/t/juce-running-on-raspbian-raspberry-pi/23321/5), as a starting point.

**Comment by ferdnyc** [comment]
Looks like you may be right about ARMv6, though there's an atomic shared library that [should make it work](https://github.com/PurpleI2P/i2pd/issues/897) on that platform. 

So if you did want to make it work with the existing compiler, you could try building **both** libopenshot-audio and libopenshot with `cmake -DCMAKE_CXX_FLAGS="-latomic" ...` (you'd want to delete or move your build dir and start fresh) to include libatomic.

**Comment by Askmewho** [comment]
fixed! I will leave this open just until I finish compiling everything

**Comment by ferdnyc** [comment]
Don't leave people in suspense! What was the fix? (Other RPi users may someday happen upon this issue report, searching for solutions to the same problem...)

**Comment by Askmewho** [comment]
indeed. I've tried your solution. but I will use a more clean one on rpi4... just compile a non retrocompatibility gcc to avoid this thing. Ive moved to buster and I forgot to do that, witch its quite needed if you want to compile projects to your specific pi and avoid these things.

**Comment by ferdnyc** [comment]
First thing I'd suggest is using `python3 setup.py`, it's possible the default Python is Python 2 which we don't support.

**Comment by ferdnyc** [comment]
> indeed. I've tried your solution. but I will use a more clean one on rpi4... just compile a non retrocompatibility gcc to avoid this thing. Ive moved to buster and I forgot to do that, witch its quite needed if you want to compile projects to your specific pi and avoid these things.

Makes sense. But linking in `libatomic` did fix things with the existing setup? Hmm. I wonder if there's a way CMake can detect which systems we'd need to do that on?

**Comment by Askmewho** [comment]
yeha I understand, but how I clean up because 

```
pi@raspberrypi:~/Desktop/openshot-qt $ python3 setup.py
Copying modules to openshot_qt directory: /home/pi/Desktop/openshot-qt/openshot_qt
Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    copytree(os.path.join(PATH, "src"), os.path.join(PATH, "openshot_qt"))
  File "/usr/lib/python3.7/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/pi/Desktop/openshot-qt/openshot_qt'

```

**Comment by ferdnyc** [comment]
Yeah, that's an... issue with the build script, when it aborts prematurely. Just `rm -r openshot_qt` before running it again.

**Comment by ferdnyc** [comment]
Actually, if that works, it's just going to show you `setup.py` usage statement. So instead try _this_:

`python3 setup.py build`

**Comment by Askmewho** [comment]
It says than "ModuleNotFoundError: No module named 'PyQt5'"
but I have pyqt5 and -dev installed. Ive tried tu install it with pip3 install but it doesnt have those binaries.. so I will have to install them from source... qt projects takes long to compile, but here we go.

**Comment by ferdnyc** [comment]
Building PyQt5 is kind of a nightmare, too, to be honest. Before going through all that I'd exhaust all options for avoiding it, first.

If you have just "pyqt5" / "pyqt5-dev" installed, it's _probably_ built for the default Python 2. I know on Fedora, we don't have a `pyqt5` package per se, because we have **two**: `python3-qt5` and `python2-qt5`. So, there might be a Python3 version accessible under some other name?

**Comment by ferdnyc** [comment]
You also need that PyQt5 to include the QtWebKit module, which it will only build if Qt has [qtwebkit](https://github.com/qt/qtwebkit) installed in it when it's built. QtWebKit is _not_ installed by default in Qt (since Qt 5.6).

**Comment by Askmewho** [comment]
yeah! sudo apt install python3-qtpy resolve the issue. waiting for finish.

**Comment by Askmewho** [comment]
it didnt look on the right paths for the libs.
Ive tried LD_LIBRARY_PATH= command just for testing porpoise but it doesnt work neither
ive got this output when executing openshot-qt.

```
pi@raspberrypi:~/Desktop/openshot-qt $ python3 src/launch.py
Loaded modules from current directory: /home/pi/Desktop/openshot-qt/src
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/openshot.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libopenshot.so.17: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/launch.py", line 103, in <module>
    main()
  File "src/launch.py", line 96, in main
    app = OpenShotApp(argv)
  File "/home/pi/Desktop/openshot-qt/src/classes/app.py", line 64, in __init__
    from classes import settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/home/pi/Desktop/openshot-qt/src/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/usr/local/lib/python3.7/dist-packages/openshot.py", line 17, in <module>
    _openshot = swig_import_helper()
  File "/usr/local/lib/python3.7/dist-packages/openshot.py", line 16, in swig_import_helper
    return importlib.import_module('_openshot')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libopenshot.so.17: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
```

**Comment by Askmewho** [comment]
ok, now preload its working, wait a moment,

**Comment by ferdnyc** [comment]
If `/usr/local/lib` isn't in your default library path, it _might_ be easier to just build `libopenshot-audio` and `libopenshot` to install into `/usr/`. That'd be `cmake -DCMAKE_INSTALL_PREFIX=/usr` during the setup phase. (You can use `python3 setup.py install --prefix=/usr` to do the same with OpenShot itself.)

Or, if the system has a `glibc` that's anything like Fedora's, you could create a file `/etc/ld.so.conf.d/local.conf` containing just the string `/usr/local/lib`, and then run `sudo ldconfig` to add libraries in that dir to the `ld` cache.

**Comment by ferdnyc** [comment]
Either way, `ldd /usr/local/lib/python3.7/dist-packages/_openshot.so` will tell you whether it's finding `libopenshot.so`, and where:
```console
$ ldd /usr/lib64/python3.7/site-packages/_openshot.so 
	linux-vdso.so.1 (0x00007ffd6cb2a000)
	libpython3.7m.so.1.0 => /lib64/libpython3.7m.so.1.0 (0x00007fa7a040d000)
	libopenshot.so.17 => /lib64/libopenshot.so.17 (0x00007fa7a02ee000)
	libopenshot-audio.so.6 => /lib64/libopenshot-audio.so.6 (0x00007fa7a0101000)
        [...]
```

**Comment by Askmewho** [comment]
after installed python3-zmq with LD_LIBRARY_PATH it ruunssss :+1: 

![2019-08-04-192132_1920x1080_scrot](https://user-images.githubusercontent.com/39385643/62429992-3ab5ad00-b6ed-11e9-8ffd-47f191ab4433.png)

**Comment by Askmewho** [comment]
leave this open for now!

**Comment by ferdnyc** [comment]
![image](https://user-images.githubusercontent.com/538020/62430047-135ae200-b6e5-11e9-9037-89189dc81d8d.png)

Hmm, seems whatever window/display manager that is doesn't support window transparency correctly, but oh well. Can't have everything!

> leave this open for now!

Will do. Though you always have the option to reopen if needed, anyway.

**Comment by Askmewho** [comment]
Thats probably the mesa videocore 4 driver hardware/software limitations.. but the newer videocore6 and his mesa driver will be much better than this.

**Comment by Askmewho** [comment]
Thats probably the mesa videocore 4 driver hardware/software limitations.. but the newer videocore6 and his mesa driver will be much better than this. 

On legacy driver the gui seems to run better. I am testing it.

**Comment by Askmewho** [comment]
I will make a review of this program on rpi4 on youtube. So far, its working great on rpi3 with some zram help.

**Comment by Askmewho** [comment]
@ferdnyc One last question, there is any defisher effect correction than I can add to these program?

**Comment by ferdnyc** [comment]
@Askmewho 

Not that I'm aware of. OpenShot doesn't really have a lot of features for processing _input_ files, the built-in effects are mostly about creating a certain... well... _effect_ in the **output** file.

Typically when an input file needs any sort of processing, I recommend that be done _before_ importing it into OpenShot, using a tool that's better suited to video correction and transcoding. (Afraid I don't have any recommendations for _those_, either, when it comes to lens correction.)

**Comment by SuslikV** [comment]
You did it! You met a lot of difficulties on your path to succeed. Not many got to this point. It's time to give achievements for successful build of the OpenShot!..

Take this:
![OpenShot S-hero](https://user-images.githubusercontent.com/19683044/62448892-7c883700-b771-11e9-99f1-dd2c7353c85e.png)


Source file (if needed, same usage as OpenShot's current license):
About 3.37 KB to download, CRC of the zip archive MD5:DB1DF7CE42FD4C06517B7C89346C082E
[OpenShot S hero.zip](https://github.com/OpenShot/libopenshot/files/3466518/OpenShot.S.hero.zip)

I designed it to use with both bright and dark backgrounds.

**Comment by Askmewho** [comment]
Many thanks! I will r3open if something happens on rpi4, so far its working great.
