### ISSUE TITLE
Attempts to use muxing_preset flags cause corrupted exports in OpenShot

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/libopenshot#292]
Mirrored from OpenShot/openshot-qt#2918

When `SetOption(openshot.VIDEO_STREAM, "muxing_preset", "mp4_faststart")` is used in the Python API by OpenShot, the exported video is not playable in `ffplay`.

At the end of export, these messages are output on the console:

```
[mp4 @ 0x562a3ba3a540] Starting second pass: moving the moov atom to the beginning of the file
[mp4 @ 0x562a3ba3a540] Unable to re-open /var/tm output file for the second pass (faststart)
```

Then, attempting to play that file in `ffplay` results in:

```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ff700000b80] moov atom not found
/var/tmp/OpenShotTest.mp4: Invalid data found when processing input 
```

(You can see there the full path name to the file, which is truncated in the output during encode. I'm not sure if that's part of the issue or not.)

**Comment by SuslikV** [comment]
Please, add steps how to reproduce the issue.

**Comment by SuslikV** [comment]
I see path as `/var/tm` in your log is it right (without `p` at the end)?

**Comment by ferdnyc** [comment]
@SuslikV `/var/tm` wasn't the path, the path was `/var/tmp/OpenShotTest.mp4`. But it was displayed as `/var/tm` in the output. As I said:
> (You can see there the full path name to the file, which is truncated in the output during encode. I'm not sure if that's part of the issue or not.)

> Still waiting for steps, man.

And I was working on that, when I decided that I should really test with a daily build instead. So I downloaded `OpenShot-v2.4.4-dev2-1564785878-90a56104-f17a7ed4-x86_64.AppImage` and tried it there, but it doesn't appear to have hit the same error:
```
[avi @ 0x6ffc620] non-interleaved AVI
[mp4 @ 0x3fd3c40] Starting second pass: moving the moov atom to the beginning of the file
[aac @ 0x3fbd080] Qavg: 65536.000
[aac @ 0x3fbd080] 1 frames left in the queue on closing
[libx264 @ 0x40d8300] frame I:21    Avg QP: 4.54  size:117959
[libx264 @ 0x40d8300] frame P:215   Avg QP: 4.56  size:  9727
[libx264 @ 0x40d8300] mb I  I16..4: 29.7% 35.0% 35.3%
[libx264 @ 0x40d8300] mb P  I16..4:  0.6%  1.1%  0.3%  P16..4: 12.3%  3.4%  4.5%  0.0%  0.0%    skip:77.8%
[libx264 @ 0x40d8300] final ratefactor: 5.97
[libx264 @ 0x40d8300] 8x8 transform intra:38.2% inter:40.9%
[libx264 @ 0x40d8300] coded y,uvDC,uvAC intra: 72.0% 77.4% 74.8% inter: 8.0% 10.1% 9.0%
[libx264 @ 0x40d8300] i16 v,h,dc,p: 44% 29%  7% 19%
[libx264 @ 0x40d8300] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu:  7% 69% 10%  2%  1%  1%  2%  1%  8%
[libx264 @ 0x40d8300] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 17% 55%  7%  3%  3%  2%  5%  1%  7%
[libx264 @ 0x40d8300] i8c dc,h,v,p: 36% 45%  5% 14%
[libx264 @ 0x40d8300] Weighted P-Frames: Y:0.9% UV:0.9%
[libx264 @ 0x40d8300] ref P L0: 94.4%  0.6%  2.8%  2.1%
[libx264 @ 0x40d8300] kb/s:4645.96
```

So, while I'm still not sure what the issue was, it appears to be a local error. I'll re-revert OpenShot/openshot-qt#2918, on the assumption that whatever was going on with my exports is confined to my exports.

My apologies for the erroneous report.

**Comment by SuslikV** [comment]
Maybe it is not erroneous, the cause of the problem is quite interesting. Just place where problem exist maybe different. Please, say if you'll find out something interesting.
