### ISSUE TITLE
Titles with default title names are overwriten sometimes, add timestamp to avoid this

### ISSUE THREAD

**Issue by rohezal** [OpenShot/libopenshot#319]
Edit: would be better placed in OpenShot/openshot-qt. Copied to it, please close this issue. Link: https://github.com/OpenShot/openshot-qt/issues/2961

I added the timestamp to the default title name to avoid overwriting it by accident.

openshot_qt/windows/title_editor.py

import time

Change Line 214:                   

self.txtFileName.setText(_("TitleFileName-%d") % i)

to

self.txtFileName.setText(str(int(time.time())) + "-" +
_("TitleFileName-%d") % i)

**Comment by ferdnyc** [comment]
@rohezal 

The reporter always has the ability to close their own issues, FYI. But, closing.
