### ISSUE TITLE
image->byteCount() marked deprecated in Qt

### ISSUE THREAD

**Issue by JackDesBwa** [OpenShot/libopenshot#323]
The byteCount method used in openshot::QtImageReader::Open() is now deprecated in Qt (at least in 5.13). It should be replaced by sizeInBytes().

**Comment by ferdnyc** [comment]
@JackDesBwa 

Good to know, but unfortunately `sizeInBytes()` was only introduced in Qt 5.10, which makes it too new for us to use. (We still have to support down to like Qt 5.5, I think.) Looks like we're stuck with `byteCount()` until they actually remove it in Qt 6.

**Comment by ferdnyc** [comment]
Fixed in #470.
