### ISSUE TITLE
We need a special-cased dissolve operation to replace the fade.svg "transition"

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/libopenshot#342]
See  OpenShot/openshot-qt#640.

**Comment by ferdnyc** [comment]
Specifically, I proposed in https://github.com/OpenShot/openshot-qt/issues/640#issuecomment-538781317 :

>  I think the only good solution to this is to stop trying to pretend that we can "trick" a crossfade into acting as a dissolve. We should do away with `fade.svg` entirely, and instead special-case a transition with a `Source` property of `None` (meaning, no transition file at all) to mean that we need to perform a simple dissolve. We can define `+1` and `-1` on the Brightness scale as the endpoints of the dissolve, so that it has the same range as all of the transitions.

**Comment by ferdnyc** [comment]
Hey, back off my issue, Stale! :wink: **#StillValid**

**Comment by rexdk** [comment]
@ferdnyc 
Sorry I didn't spot this one in 3632. Just adding some more detail about one approach to resolve this.
Currently as far as I can see, the alpha of the first clip is adjusted as 'brightness' changes thus:
![transmap3](https://user-images.githubusercontent.com/44414261/89024945-e05e2500-d31d-11ea-9a8a-9a03eb11eb94.png)
where white/grey/black are pixel colours on the mask. This is easy and quick to calculate.
An alternative would be:
![transmap1](https://user-images.githubusercontent.com/44414261/89025072-1bf8ef00-d31e-11ea-9ead-203f064c4d69.png)
There are 2 options for eg a grey halfway between black and # 777777:
![transmap2](https://user-images.githubusercontent.com/44414261/89025206-53679b80-d31e-11ea-9e05-98f35e91df33.png)
I think the single straight line is nearer to what we have currently.

The formula would be: alpha = (v<0.5) ? (b+2v)/(1+2v) : (b+1)/(3-2v)   (I think)
where v is the HSV value of the mask pixel and b is the 'brightness'

This would probably resolve it, except that it requires more processing. I'm not sure to what extent that is a worry nowadays. The processing is only over the period of the transition.

There would be a small effect on existing greyscale transitions, but maybe not noticeable.
The Fade transition could be kept for existing projects, and a new all-grey cross-fade transition introduced

============

The other thing about transitions in general is that the common ones need to be clearly separated at the top, so the user is not confused by the rarely used weird transitions. 'Fade' could then be dumped in the weird category ;)

**Comment by rexdk** [comment]
Argh! - I have just discovered that there is a tab to show just the common transitions. Now, I may be the only person in the universe to have missed this  - but I generally find it easy to cotton on. So I think this tells us that even if it is obvious,  it is not obvious enough. 

I think it should default to display just the common transitions. As it is at the moment it is saying to the user, "look how smart the developers are, they've included 397 different transitions." The user should first see the basics; the UI should say, "look how easy it is to use Openshot."

**Comment by rexdk** [comment]
@ferdnyc 
I've now had a closer look at this, and have quickly mocked up my proposal in js:
https://www.drking.org.uk/trans/

It certainly solves the crossfade issue. It might be necessary to apply some contrast adjustment to the masks  to mimic the current behaviour with 'lots of grey' transition masks more closely. The code for that is already present in OpenShot.

I don't have a linux system so I can't test this in OpenShot. But I think the code would be something like this:
```
		// Calculate alpha adjustment (declare it somewhere as int)
		alpha_adjustment = (gray_value < 128) ?
					255 * (128 * brightness_value + gray_value)/(128 + gray_value) : 32385 * (brightness_value + 1)/(382 - gray_value);
						// does this need to be specifically (cast)? 

		// Constrain should be unnecessary - I think... But what about rounding errors? Be safe
		alpha_adjustment = constrain(alpha_adjustment);
				
		// Set the alpha channel or show image for testing
		if (replace_image) {
			// Replace frame pixels with gray value
			pixels[byte_index + 0] = alpha_adjustment;
			pixels[byte_index + 1] = alpha_adjustment;
			pixels[byte_index + 2] = alpha_adjustment;
		} else {
			// Set alpha channel
			A = pixels[byte_index + 3];
			pixels[byte_index + 3] = constrain(A - alpha_adjustment);
		}

```
replacing the relevant bit around line 130 in effects/Mask.cpp

As with any change to an existing behaviour it needs careful thinking about, to try not to upset existing projects, yet solve a long standing issue. A 'question of balance' decision, but not mine :). Hope this is a help.

**Comment by ferdnyc** [comment]
> As it is at the moment it is saying to the user, "look how smart the developers are, they've included 397 different transitions." 

Heh. You should definitely never right-click on any of the keyframe curve icons, then. (The ones that appear next to a value in Properties, once there are 2+ keyframe points set for it on that clip.)

Never let it be said the user isn't given options! Overwhelming, indecipherable options. :roll:

**Comment by ferdnyc** [comment]
(As for the rest, I will definitely take a look at it soon, sorry for the delay. I'm on my phone right now and the GitHub app, while pretty ok for communicating, is absolute shit for even reading code. Everything is in way too large a font and it's impossible to get your bearings.)

**Comment by rexdk** [comment]
Oh yes, I know about the myriad Bezier curves. Really looking forward to documenting those - not. Probably have to look in the code to find out what they do.

No rush with this, I know how it is. If you do want to go go the route of one simple special case crossfade instead, then the implementation is presumably easy enough, if you can pass a flag for that transition being used.

**Comment by rexdk** [comment]
Oh great. Well, if there were very few bugs and lots of people working on them I suppose it would be OK. Sadly the reverse is the case, and I guess we have to live with most issues being closed unresolved and regularly rediscovered by other users.

I was going to propose a load of changes to the transition system, as it is pretty make-do at the moment (no audio fades, multiple tramsitions created by moving a clip, inability to drag and replace a transition, transitions don't adjust size on clip move, need for preference settings, and some more subtle and powerful stuff). It'll have to wait until there is a chance it might get done.

**Comment by rexdk** [comment]
still an issue in a recent daily build
