### ISSUE TITLE
SetVideoOptions does not set info members

### ISSUE THREAD

**Issue by xdmtk** [OpenShot/libopenshot#347]
Hi all, 

```
    auto writer = openshot::FFmpegWriter(parameter->blank_file);
    writer.SetVideoOptions(true,
         "mpeg4",
        openshot::Fraction(parameter->fps,1),
        frame_width,
        frame_height,
         openshot::Fraction(1,1),
         false,
         false,
         30000);

    /* Generate a blank frame */
    auto blank_frame = new openshot::Frame(1, frame_width, frame_height, "#000000");
    auto p_frame = std::shared_ptr<openshot::Frame>(blank_frame);

    /* Open the destination empty video */
    writer.Open();
    if (!writer.IsOpen()) {
        return false;
    }
```

After running this code, `libopenshot` throws an exception at `writer.Open()` 

```
terminate called after throwing an instance of 'openshot::InvalidOptions'
  what():  No video or audio options have been set.  You must set has_video or has_audio (or both).
```

A bit stumped on this one since the call to `SetVideoOptions()` should have set `info.has_video` to true, as shown in

```
if (!info.has_audio && !info.has_video)
  505                 throw InvalidOptions("No video or audio options have been set.  You must set has_video or has_audio (or both).", path);
```

But it is not. What am I missing here?

**Comment by ferdnyc** [comment]
@xdmtk Hm... I'm not immediately sure.

There's example code in the source distribution at `src/examples/Example.cpp` (by default it compiles to `$build_dir/src/openshot-example` when libopenshot is built), perhaps you can compare it against your code to pin down the pivotal difference that's tripping up FFmpegWriter?

**Comment by xdmtk** [comment]
@ferdnyc Thanks for the prompt response! Some how, some way, whatever issue I'm finding seems to be specific to only one machine I run it on.. very odd. Though I'll keep investigating and if I find anything I'll post on the issue. 

Worth it to leave it open for now?

**Comment by ferdnyc** [comment]
@xdmtk Mmm... honestly, given the weirdness, probably not. I'm going to close — the issue can always be reopened if necessary (and feel free to do so, if you discover any new details about the problem).

**Comment by ferdnyc** [comment]
(Could be that the difference is something to do with FFmpeg version, or build configuration. We have a _lot_ of code in `include/FFmpegUtilities.h` (not to mention the `FFmpeg{Reader,Writer}.cpp` files themselves) that's conditional on various FFmpeg version levels and/or feature `#define`s, and I wouldn't want to bet on it all being 100% solid across all possible versions and combinations of their wacky moving-target APIs.)
