### ISSUE TITLE
We're using a deprecated ZeroMQ method

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/libopenshot#353]
This is just a reminder, mostly for myself, that a deprecation warning is emitted during builds of libopenshot against very-recent ZeroMQ releases (Fedora 30 is on 4.3.2 now):

```
src/ZmqLogger.cpp: In member function ‘void openshot::ZmqLogger::Log(std::string)’:
src/ZmqLogger.cpp:126:23: warning: ‘bool zmq::detail::socket_base::send(zmq::message_t&, int)’
is deprecated: from 4.3.1, use send taking message_t and send_flags [-Wdeprecated-declarations]
  126 |  publisher->send(reply);
      |                       ^
In file included from src/../include/ZmqLogger.h:43,
                 from src/ZmqLogger.cpp:31:
/usr/include/zmq.hpp:1191:10: note: declared here
 1191 |     bool send(message_t &msg_,
      |          ^~~~
```
Not sure yet if the "`send` taking `message_t` and `send_flags`" signature exists in all earlier versions of ZeroMQ, or if we're going to have to special-case the code by version.

**Comment by musteresel** [comment]
`send` with `message_t` and `send_flags` is a relatively recent addition ([this commit](https://github.com/zeromq/cppzmq/commit/3d4be814e8a6cb44e39ddc7c272bdcc1ffad296f)) ... as far as I can see the new functions are thus only there since two releases (half a year)

**Comment by ferdnyc** [comment]
@musteresel Thanks! That's a quick deprecation, then... hrm.

Guess we'll have to get conditional, we certainly wouldn't be safe assuming that we can use the replacement API with every version of ZeroMQ that might be linked into `libopenshot`.

**Comment by ferdnyc** [comment]
Oops, I just merged the patch for this, but didn't tag it. Closing as fixed in... #470
