### ISSUE TITLE
using FFmpegWriter for mpeg-ts files

### ISSUE THREAD

**Issue by chad3814** [OpenShot/libopenshot#363]
I can't seem to get FFmpegWriter to create a `.ts` output file. Here is some minimal example code:
```
#include <OpenShot.h>

int main(int argc, char *argv[]) {
    ZmqLogger::Instance()->Enable(true);
    ZmqLogger::Instance()->Path("/dev/stdout");

    FFmpegReader r("/home/chad/manual/xkbr844wq40599w1k2w428hm.mp4");
    r.Open();
    FFmpegWriter w("/home/chad/manual/xkbr844wq40599w1k2w428hm.ts");

    w.SetAudioOptions(true, "aac", 44100, 2, ChannelLayout::LAYOUT_STEREO, 128000);
    w.SetVideoOptions(true, "libx264", openshot::Fraction(30, 1), 1280, 720, openshot::Fraction(1, 1), false, false, 7000000);

    // Open the writer
    w.Open();

    int64_t one = static_cast<int64_t>(1);
    int64_t length = r.info.duration * 30;
    w.WriteFrame(&r, one, length);
    r.Close();
    w.Close();
}
```
It always fails with:
```
[mpegts @ 0x55ea99cdf880] AAC packet too short
```
around the 24th `Frame`. I've tried with different mp4's, all of which I can convert fine with command-line `ffmpeg`. I'm just not sure what I'm doing wrong or need to do differently. If I change the file extension to `.mp4` it works fine, so it's something specific to the mpeg-ts container, I guess.

Any ideas?

(the video I used is at [https://cdn-ascope-prod.global.ssl.fastly.net/static/videos/xkbr844wq40599w1k2w428hm.mp4](https://cdn-ascope-prod.global.ssl.fastly.net/static/videos/xkbr844wq40599w1k2w428hm.mp4))

**Comment by SuslikV** [comment]
I think ADTS "framing" required for the mpeg-ts files:
https://wiki.multimedia.cx/index.php/ADTS

**Comment by ferdnyc** [comment]
It looks like it might be even more complicated than that.

FFmpeg has [a whole dedicated `mpegts` muxer](https://ffmpeg.org/ffmpeg-formats.html#mpegts-1), to get a strict, broadcast-standards MPEG-TS container that muxer [should be used](https://www.advanceddigital.com/blog/introduction-to-ffmpeg-for-broadcast-engineers/). There's also an `adts` audio encoding format/muxer, which doesn't appear to be documented but it's listed in the output of `ffmpeg -formats`. However, the impression I get is that using `-f mpegts` as the muxer will automatically add ADTS headers to the audio stream.

AFAIK `libopenshot` doesn't currently provide any way to select or configure the `mpegts` muxer for the output data, though. (But I could be wrong about that.) Specifying `.ts` as the output file extension may not be sufficient. (@chad3814 's results so far would seem to indicate that it's not.)
