### ISSUE TITLE
Improve export render quality

### ISSUE THREAD

**Issue by PanderMusubi** [OpenShot/libopenshot#37]
Improve export render quality by setting more options for FFmpeg and using a two-pass rendering.

My attempt for it is in https://github.com/z25/libopenshot Come join the party and help out to make OpenShot render non-jerky videos.

**Comment by PanderMusubi** [comment]
Initial goals is to improve H.264 quality to be non-jerky. See:
* https://www.ffmpeg.org/doxygen/0.6/structAVCodecContext.html
* https://trac.ffmpeg.org/wiki/Encode/H.264
* http://slhck.info/video-encoding
* https://stackoverflow.com/questions/31858171/two-pass-encoding-in-ffmpeg
* https://www.virag.si/2012/01/web-video-encoding-tutorial-with-ffmpeg-0-9/

**Comment by Windsurfer01** [comment]
Openshot version 1 did not have this problem on my PC,but 2.1 does. It may indicate two possibilities:
1) The current version of ffmpeg has a problem.
2) Using the settings that were in Openshot v1 will work better.

**Comment by PanderMusubi** [comment]
Meanwhile I have switched to Kdenlive due to deadline. Hope to switch back once this has been improved.

**Comment by osirisinferi** [comment]
Also, 1 pass ABR is a really inefficient encoding setting for x264.

I'd like to see CRF encoding, which makes much more sense.
