### ISSUE TITLE
Could NOT find FFMPEG (missing:  FFMPEG_LIBRARIES FFMPEG_INCLUDE_DIR) 

### ISSUE THREAD

**Issue by stephenwithav** [OpenShot/libopenshot#4]
I'm having trouble with `cmake ..`.

I successfully installed `libopenshot-audio` with no trouble and have the `ffmpeg`/`libav*` libraries installed from [source](https://github.com/ffmpeg/ffmpeg), but `cmake` claims the ffmpeg libraries don't exist.

```
-------------------------------------------------------------
Welcome to the OpenShot Build System! CMake will now check for all required build
dependencies and notify you of any missing files or other issues. If you have any
questions or issues, please visit <http://www.openshot.org/>.
--------------------------------------------------------------
Determining Version Number (from Version.h file)
--> MAJOR Version: 0
--> MINOR Version: 0
--> BUILD Version: 5
--> SO/API/ABI Version: 3
--> VERSION: 0.0.5

CMake Warning (dev) at CMakeLists.txt:66 (PROJECT):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
This warning is for project developers.  Use -Wno-dev to suppress it.

--------------------------------------------------------------
Generating build files for openshot (0.0.5)
-- Could NOT find FFMPEG (missing:  FFMPEG_LIBRARIES FFMPEG_INCLUDE_DIR) 

'LIBOPENSHOT_AUDIO_INCLUDE_DIRS:/usr/local/include/libopenshot-audio'
-- Could NOT find Ruby (missing:  RUBY_EXECUTABLE RUBY_INCLUDE_DIR RUBY_LIBRARY) 
-- Could NOT find FFMPEG (missing:  FFMPEG_LIBRARIES FFMPEG_INCLUDE_DIR) 

CMake Warning (dev) at tests/CMakeLists.txt:176 (ADD_CUSTOM_TARGET):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/UseDoxygen.cmake:137 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "doc".
Call Stack (most recent call first):
  CMakeLists.txt:84 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
AVRESAMPLE_INCLUDE_DIR
   used as include directory in directory /home/steven/goprojects/github.com/OpenShot/libopenshot/src
   used as include directory in directory /home/steven/goprojects/github.com/OpenShot/libopenshot/src
   used as include directory in directory /home/steven/goprojects/github.com/OpenShot/libopenshot/src
   used as include directory in directory /home/steven/goprojects/github.com/OpenShot/libopenshot/src/bindings/python
   used as include directory in directory /home/steven/goprojects/github.com/OpenShot/libopenshot/tests
   used as include directory in directory /home/steven/goprojects/github.com/OpenShot/libopenshot/tests
AVRESAMPLE_LIBRARY
    linked by target "openshot" in directory /home/steven/goprojects/github.com/OpenShot/libopenshot/src

-- Configuring incomplete, errors occurred!
See also "/home/steven/goprojects/github.com/OpenShot/libopenshot/build/CMakeFiles/CMakeOutput.log".
```

`libavresample`, for example, exists at `/usr/lib/x86_64-linux-gnu/libavresample.so.2`.

How do I fix this?

**Comment by wittenbe** [comment]
I'm not sure what's wrong here, but you won't have much success with the latest ffmpeg version anyway, since (apparently) there have been some changes regarding PixelFormat and openshot hasn't adjusted yet. Ubuntu 14.04's libavcodec-dev etc seem to work fine though (be sure to sudo make uninstall your ffmpeg if you go down that route).

For reference, I configured ffmpeg with --prefix=/usr/local and cmake found everything just fine. Alternatively you can edit the CMakeCache (with ccmake, cmake-gui, or a text editor) and set the lib paths manually.

**Comment by stephenwithav** [comment]
Thank you, @wittenbe.  Using `apt-get` to install the libav* libraries allowed me to compile libopenshot.

**Comment by sxiii** [comment]
@stephenwithav this approach hadn't worked for ubuntu 20.04, however, 

```sudo apt install libavcodec-dev libavformat-dev libavfilter-dev```

solved everything for me.

**Comment by wmww** [comment]
On Ubuntu 20.10 I've apt installed `libavcodec-dev libavformat-dev libavfilter-dev`, but CMake is failing to find `avdevice`, `avfilter` and `postproc`. There's more output than normal because I've uncommented some messages in `cmake/Modules/FindFFmpeg.cmake`:

<details>

```
wmww@wmwwXPS:~/code/media/libopenshot/build$ cmake .. -DOpenShotAudio_ROOT=/home/wmww/code/media/libopenshot/../libopenshot-audio/install
-----------------------------------------------------------------
          Welcome to the OpenShot Build System!

CMake will now check libopenshot's build dependencies and inform
you of any missing files or other issues.

For more information, please visit <http://www.openshot.org/>.
-----------------------------------------------------------------

Generating build files for OpenShot with CMake 3.16.3
  Building libopenshot (version 0.2.5)
  SO/API/ABI Version: 19

-- Creating IMPORTED target OpenShot::Audio
-- Looking for system jsoncpp
-- FFmpeg - avcodec found.
-- FFmpeg - avdevice not found.
-- FFmpeg - avformat found.
-- FFmpeg - avfilter not found.
-- FFmpeg - avutil found.
-- FFmpeg - postproc not found.
-- FFmpeg - swscale found.
-- FFmpeg - swresample found.
-- FFmpeg - avresample found.
-- Requested component avcodec present.
-- Requested component avdevice missing.
-- Requested component avformat present.
-- Requested component avutil present.
-- Requested component swscale present.
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find FFmpeg (missing: avdevice_LIBRARIES avdevice_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindFFmpeg.cmake:231 (find_package_handle_standard_args)
  src/CMakeLists.txt:275 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/wmww/code/media/libopenshot/CMakeFiles/CMakeOutput.log".
```</details>

**Comment by ferdnyc** [comment]
@wmww 

After installing additional components, did you restart from a _clean_ build tree? CMake will cache the results of previous probes, which can get you in trouble if you've changed what those results would be. I usually recommend completely deleting the build directory and letting CMake create it again. (With modern CMake, you can run it from the root of the repo without having to `cd` into the build tree, which makes it really easy to `rm -r build` between runs. I typically build like this:
```sh
cd /path/to/libopenshot
cmake -B build -S . -DCMAKE_INSTALL_PREFIX=build/dist \
  -DOpenShotAudio_ROOT=/path/to/libopenshot-audio/install/root
cmake --build build --verbose
cmake --install build
```
If the build messes up at all... well, at this point I'm usually confident enough that I can just `rm build/CMakeCache.txt` and re-run `cmake`, but if I ever need to change the build type or something fundamental like that, I'm always sure to `rm -r build; cmake -B build -S . ...`

**Comment by ferdnyc** [comment]
Beyond that, I'm kind of at a loss. If all of the correct FFmpeg components are installed, there's no reason they shouldn't be found. Do you see a `libav____.so.MM.NN.PPP` in `/usr/lib/x86_64-linux-gnu/` for each of the components being probed for? How about 
a `.pc` file in `/usr/lib/x86_64-linux-gnu/pkgconfig/`? FindFFmpeg should use pkg-config to discover the ffmpeg libraries, as a first resort.

**Comment by ferdnyc** [comment]
You can also add `--trace-source=FindFFmpeg.cmake` to the CMake command line, to trace the find module as it executes. The output is _verbose_ — and surprisingly unhelpful, really, for all of that verbosity — but if all else fails, it may provide a clue.

**Comment by wmww** [comment]
Thanks for the helpful tips! I got it built.

`cmake -B build -S .` works but cding into the directory and running `cmake ..` fails to find libavdevice, even when the rest of the CMake arguments are absolute paths and exactly the same. I blew away the build directory and recreated it several times for both methods, and the latter always fails. I don't understand CMake well enough to figure that out and I don't particularly care now that it works, but it is strange.

**Comment by ferdnyc** [comment]
@wmww 

> `cmake -B build -S .` works but cding into the directory and running `cmake ..` fails to find libavdevice, even when the rest of the CMake arguments are absolute paths and exactly the same.

That's _bizarre_! Glad to hear you got it built, though. 

If it's not too much trouble, I'd really like to see the contents of the `debug_find.out` file produced by:
```sh
cd /path/to/libopenshot
mkdir debug_find
cd debug_find
cmake .. --debug-find 2>&1 | tee debug_find.out
```

...See if I can figure out what's going on there. (Add in any other command line args you need, obviously.)

Oh, and ideally also the `./CMakeFiles/CMakeOutput.log` file from the build directory.

**Comment by wmww** [comment]
Unfortunately it looks like the Ubuntu 20.10 CMake (3.16.3) is too old for `--debug-find` (introduced in 3.17, according to [this](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_DEBUG_MODE.html)).

**Comment by wmww** [comment]
I've discovered the difference is that in the `cmake ..` case the variable `FFmpeg_LIBRARIES` is set before entering `FindFFmpeg.cmake`, while in the `cmake -B build` case it's not (this results in different logic in `FindFFmpeg.cmake`). I don't know why it's being set for the former, but `message(STATUS "FFmpeg_LIBRARIES: ${FFmpeg_LIBRARIES}")` at the very top of the root `CMakeLists.txt` shows

```
-- FFmpeg_LIBRARIES: /usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavutil.so;/usr/lib/x86_64-linux-gnu/libswscale.so
```

in the former case but it's empty in the latter.

I've tried deleting the build dir and recreating it with the same results.

**Comment by ferdnyc** [comment]
@wmww 

Huh! Stranger and stranger.

Seems like some sort of local distro modification. I tried it myself on Fedora 32, with the same `message()` command immediately after the `project()` line in the root `CMakeLists.txt`. and as expected I got:
<pre><code>
$ cmake ..
-----------------------------------------------------------------
          Welcome to the OpenShot Build System!

CMake will now check libopenshot's build dependencies and inform
you of any missing files or other issues.

For more information, please visit <http://www.openshot.org/>.
-----------------------------------------------------------------
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
<b>-- FFmpeg_LIBRARIES: </b>

Generating build files for OpenShot with CMake 3.17.4
  Building libopenshot (version 0.2.5)
  SO/API/ABI Version: 19
</code></pre>

**Comment by ferdnyc** [comment]
@wmww I admit I'm grasping at straws here, but... I know you said you blew away the build directory, but make sure you don't have any build files in your _source_ directory. If you ever accidentally triggered an in-source build (meaning, if there are a `CMakeFiles` directory or a `CMakeCache.txt` file in the root of the libopenshot source tree), it's possible CMake could be picking up on those and using them in the `cmake ..` build. It would be less likely to do that with a `cmake -B build -S .` build, because you've explicitly told it where _both_ the build and source dirs are. (By the same token, a `cmake -B . -S ..` from within the build directory might succeed where `cmake ..` fails.)

**Comment by wmww** [comment]
That was it! I had a CMakeLists.txt in my source root, and after removing it both methods work normally. That was a weird one. Thanks for your help.

**Comment by ferdnyc** [comment]
@wmww I am as surprised as anyone — if not _more_ — that I pulled that idea out of my a--, believe me! But, glad to hear we've finally gotten to the bottom of that craziness!

**Comment by lxhom** [comment]
@wmww oh my god thank you, i've been stuck on this on a completely unrelated project for like 30 minutes now and that solved it. tysm

**Comment by ferdnyc** [comment]
. o O (Hey, why does @wmww get all the credit for that???) :wink:
