### ISSUE TITLE
build libopenshot in linux errors

### ISSUE THREAD

**Issue by eternalsilencer** [OpenShot/libopenshot#403]
when I finished fllow cmd, start to make test and doc, but i can't find that two files,

cd [libopenshot repo directory]
mkdir -p build
cd build
cmake ../
make

and then i use python3 import openshot,fellow error happen, how can i solve this

>>> import openshot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/openshot.py", line 28, in <module>
    _openshot = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/openshot.py", line 24, in swig_import_helper
    _mod = imp.load_module('_openshot', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.5/dist-packages/_openshot.so: undefined symbol: _ZNK8openshot8Keyframe7GetLongEl
>>> 

``

**Comment by eternalsilencer** [comment]
I have solved，i missing doxygen tool

**Comment by ferdnyc** [comment]
As far as testing the Python module, you can run it from the build directory after compiling by setting `PYTHONPATH`. e.g:
```sh
mkdir build; cd build
cmake ..
make
PYTHONPATH="src/bindings/python" python3
```
```python
>>> import openshot
>>> import sys
>>> print(sys.modules['openshot'])
<module 'openshot' from '...libopenshot/build/src/bindings/python/openshot.py'>
>>> print(openshot.Version)
0.2.3-dev1
```
