### ISSUE TITLE
Crash when moving in timeline

### ISSUE THREAD

**Issue by PurpleAlien** [OpenShot/libopenshot#404]
I'm seeing the following in the libopenshot log:

```
------------------------------------------
------------------------------------------
libopenshot logging: Tue Dec 31 11:57:37 2019
------------------------------------------
---- Unhandled Exception: Stack Trace ----
  /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libgomp.so.1        0x1acbe  [0x7f7bee2d8cbe]
  /lib64/libpthread.so.0                                                     0x8397  [0x7f7c05d3f397]
  /lib64/libc.so.6               clone                                        0x3f  [0x7f7c05c6e04f]
---- End of Stack Trace ----
---- Unhandled Exception: Stack Trace ----
```

Any ideas where to start looking?

More info: this usually happens when moving the timeline, in the openshot-qt.log:

```
preview_thread:INFO previewFrame: 1594
preview_thread:INFO self.player.Position(): 1594
```

I'm running on Gentoo Linux, OpenShot version 2.4.4, libopenshot version 0.2.4 with GCC 9.2. Libopenshot on Gentoo is pulled in from commit 0d4ea7fe71e88bcee4a7fd1404bd52c8e2169997 but I've tried the latest devel version as well and run into the same problem.

Let me know what other info you'd need.

**Comment by SuslikV** [comment]
Can you try `develop` branch of the OpenShot and at least enable debug in the main menu `Edit>Preferences>Debug tab>Debug Mode (Verbose)` ?

**Comment by PurpleAlien** [comment]
Ok, after using the latest versions of everything from git I can't seem to replicate the issue. Thanks!
