### ISSUE TITLE
The .m4v extension isn't recognised for video files

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/libopenshot#417]
1. Handbrake has generated a .m4v file what isn't recognised by OpenShot...

_Originally posted by @lutzig in https://github.com/OpenShot/openshot-qt/issues/1769#issuecomment-402205159_

Looking at `src/Clip.cpp`, `m4v` isn't on the list of video file extensions, but it should be.

https://github.com/OpenShot/libopenshot/blob/49972b21e9b5f3cab08d7882b93c1f37dc6577ac/src/Clip.cpp#L164-L171

**Comment by ferdnyc** [comment]
(So should `m4a`, for that matter.)

**Comment by ferdnyc** [comment]
That lookup could also be rewritten to use a `std::unordered_set` and the `find()` method, e.g.:
```c++
const std::unordered_set<std::string> extensions = {"avi", "mov", "mkv", "mpg", /* etc... */ };

auto search = extensions.find(ext);
if (search != extensions.end()) {  // Found
   try {
        // etc...
```

**Comment by SuslikV** [comment]
This also can be string with the space as separator `"avi mov mkv mpg"`. Or integer number (up to 4 symbols) that will be processed even faster.

**Comment by ferdnyc** [comment]
@stale Begone, bot!
