### ISSUE TITLE
Loss of quality when creating square (1:1) video

### ISSUE THREAD

**Issue by jeffski** [OpenShot/libopenshot#419]
I've been trying to create square 1:1 aspect ratio videos where the source footage is 16:9. Using a simple script for testing I have noticed that there is quite an obvious drop in quality when resizing and cropping the video. Is it possible libopenshot is causing this issue with the way that it resizes and crops videos in the Timeline?

Below are my scripts and sample outputs.

**16:9 Video**
```
int main(int argc, char *argv[]) {
	Clip clip1(new FFmpegReader("clip1.mp4"));
	clip1.Position(0.0);
	clip1.Layer(1);
	clip1.Start(0.0);
	clip1.End(10.0);
	clip1.scale = SCALE_CROP;

	Timeline timeline(1280, 720, Fraction(25,1), 44100, 2, LAYOUT_STEREO);
	timeline.AddClip(&clip1);
	timeline.Open();

	FFmpegWriter writer("/tmp/output-16-9.mp4");
	writer.SetAudioOptions(true, "aac", 44100, 2, LAYOUT_STEREO, 128000);
	writer.SetVideoOptions(true, "libx264", Fraction(25, 1), 1280, 720, Fraction(1,1), false, false, 0);
	writer.PrepareStreams();
	writer.SetOption(VIDEO_STREAM, "crf", "23" );
	writer.WriteHeader();
	writer.Open();
	writer.WriteFrame(&timeline, 0, clip1.Duration() * 25);

	writer.Close();
	timeline.Close();

	return 0;
}
```

**1:1 Video**
```
int main(int argc, char *argv[]) {
	Clip clip1(new FFmpegReader("clip1.mp4"));
	clip1.Position(0.0);
	clip1.Layer(1);
	clip1.Start(0.0);
	clip1.End(10.0);
	clip1.scale = SCALE_CROP;

	Timeline timeline(720, 720, Fraction(25,1), 44100, 2, LAYOUT_STEREO);
	timeline.AddClip(&clip1);
	timeline.Open();

	FFmpegWriter writer("output-1-1.mp4");
	writer.SetAudioOptions(true, "aac", 44100, 2, LAYOUT_STEREO, 128000);
	writer.SetVideoOptions(true, "libx264", Fraction(25, 1), 720, 720, Fraction(1,1), false, false, 0);
	writer.PrepareStreams();
	writer.SetOption(VIDEO_STREAM, "crf", "23" );
	writer.WriteHeader();
	writer.Open();
	writer.WriteFrame(&timeline, 0, clip1.Duration() * 25);

	writer.Close();
	timeline.Close();

	return 0;
}
```
Results:
![16-9](https://user-images.githubusercontent.com/1064199/73258503-ef063b00-4219-11ea-8eae-f1f75c2e5c37.png)

![1-1](https://user-images.githubusercontent.com/1064199/73258484-e57cd300-4219-11ea-9260-fe04dc53982c.png)

Below are links to a frame from each video and also links to the actual videos:

16:9 Still: https://shillitto.s3-ap-southeast-2.amazonaws.com/openshot/16-9.png
16:9 Video: https://shillitto.s3-ap-southeast-2.amazonaws.com/openshot/output-16-9.mp4

1:1 Still: https://shillitto.s3-ap-southeast-2.amazonaws.com/openshot/1-1.png
1:1: Video: https://shillitto.s3-ap-southeast-2.amazonaws.com/openshot/output-1-1.mp4

This is the source video to recreate but any video should show the same loss of quality: 
https://shillitto.s3-ap-southeast-2.amazonaws.com/openshot/clip1.mp4

**Comment by jeffski** [comment]
These two videos also highlights the issue well. If you look at the thin tree trunks, they are sharp in the 16:9 video but in the 1:1 they are all pixelated/broken with a kind of wavey/spiral effect going on.

16:9: https://shillitto.s3-ap-southeast-2.amazonaws.com/openshot/output-16-9-clip2.mp4
1:1: https://shillitto.s3-ap-southeast-2.amazonaws.com/openshot/output-1-1-clip2.mp4

**Comment by ferdnyc** [comment]
@jeffski 

Here's the first 5 seconds of _OpenShot_ performing that same `SCALE_CROP` reduction to `720x720`, on your source `clip1`. To my eye, at least, it looks much clearer.

[clip1-openshot.zip](https://github.com/OpenShot/libopenshot/files/4122217/clip1-openshot.zip)

That makes me suspect that setting `openshot::Settings::Instance()->HIGH_QUALITY_SCALING` to `true` (which will switch FFmpeg's scaling from `SWS_FAST_BILINEAR` scaling to `SWS_BICUBIC`, when performing the `SCALE_CROP`) is the key factor.

**Comment by jeffski** [comment]
@ferdnyc Thanks for that, I never explored the settings before. It is definitely an improvement but it is still not as good as the 16:9 clip. I will investigate further, am I right in thinking the Timeline class is where all the scaling/cropping happens and that would be the best place to start looking?

**Comment by ferdnyc** [comment]
@jeffski AFAICT, yeah.

I mean, the video _is_ being scaled down, so there's going to be some loss of detail. (The 16:9 version is also scaled down, of course, so it's not unreasonable to expect _similar_ loss of detail.)

It's possible that the `SCALE_CROP` version effectively gets scaled _twice_: once to adjust for the reduced output resolution, then a second time for the aspect ratio change. That's particularly likely if setting `HIGH_QUALITY_SCALING` isn't necessary to get good results from the `1280x720` export. If that's the case, then most likely **that** scaling operation is being done via a QImage transform (and is always fairly high-quality), whereas `SCALE_CROP` has FFmpeg scale the frames (and therefore is affected by the `HIGH_QUALITY_SCALING` switch).

**Comment by ferdnyc** [comment]
> @jeffski AFAICT, yeah.
 > It's possible that the `SCALE_CROP` version effectively gets scaled _twice_: once to adjust for the reduced output resolution, then a second time for the aspect ratio change. 

(Not necessarily in that order.)

**Comment by SuslikV** [comment]
It has no sense to use SWS_BICUBIC - it only converts color planes in FFmpeg of already resized images, I said about that a couple of times. But you trying to make obvious thing more complex. Transform from Qt is **always bilinear** (or even point). Should link the issue here?
