### ISSUE TITLE
not find solution for this error

### ISSUE THREAD

**Issue by ohquait** [OpenShot/libopenshot#432]
git pull  branch is develop 
Merge pull request #431 from OpenShot/merge-master-into-develop
Latest commit
56af4eb
15 hours ago

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/quait/src/rpm/BUILD/libopenshot-2.4.4/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_0a716/fast && /usr/bin/gmake -f CMakeFiles/cmTC_0a716.dir/build.make CMakeFiles/cmTC_0a716.dir/build
gmake[1]: Entering directory '/repm/src/rpm/BUILD/libopenshot-2.4.4/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_0a716.dir/src.c.o
/usr/bin/cc   -O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_0a716.dir/src.c.o   -c /home/quait/src/rpm/BUILD/libopenshot-2.4.4/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_0a716
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0a716.dir/link.txt --verbose=1
/usr/bin/cc -O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -DCMAKE_HAVE_LIBC_PTHREAD  -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id  CMakeFiles/cmTC_0a716.dir/src.c.o  -o cmTC_0a716 
/usr/bin/ld: CMakeFiles/cmTC_0a716.dir/src.c.o: in function `main':
src.c:(.text.startup+0x13): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text.startup+0x1d): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text.startup+0x29): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_0a716.dir/build.make:87: cmTC_0a716] Error 1
gmake[1]: Leaving directory '/repm/src/rpm/BUILD/libopenshot-2.4.4/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_0a716/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

**Comment by ohquait** [comment]
on /usr/share/cmake/cppzmq/cppzmqConfig.cmake
have to commented line 60
from 
  get_target_property(cppzmq_STATIC_LIBRARY libzmq-static LOCATION)
to
#  get_target_property(cppzmq_STATIC_LIBRARY libzmq-static LOCATION)

while no static-lib is installed,
so this is not a error in openshot-codes, error on my system

solved

**Comment by ferdnyc** [comment]
@ohquait What OS are you building on?

I only ask because, I'm on Fedora 31, and the files in my `/usr/share/cmake/cppzmq/` directory (which come from the `cppzmq-devel-4.5.0-1.fc31.x86_64.rpm` package) sound like they have very different contents than yours. I'm curious what we might be able to do to make our CMake configs more compatible with the installed files, without having to modify them.

**Comment by ohquait** [comment]
I use PCLinuxOS,


Frank Dana <notifications@github.com> schrieb am Mo., 10. Feb. 2020, 01:59:
