### ISSUE TITLE
BlackMagic support still useful?

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/libopenshot#444]
The BlackMagic DeckLink support in libopenshot has been kicking around forever, in the form of a `FindBlackMagic.cmake` module to link with their libs, and the `DeckLinkReader` and `DeckLinkWriter` classes that are enabled if they're found.

But is that support actually in _use_ anywhere?

As far as I can tell no official OpenShot binaries are built with DeckLink support, and none of the builds in our CI matrix ever test that code. I know for a _fact_ `FindBlackMagic.cmake` is woefully out of date. (Not to mention, includes hardcoded `/home/jonathan/...` paths in the search locations for the BlackMagic SDK.) I _assume_ the actual Reader/Writer classes still work, though because they're never tested that's really only an assumption... and it's assuming they **originally** worked, since really I have no way of even knowing that.

I'm still working to prune our build process, and by extension the repo, of outdated, unused cruft that's lying around. (There's a FindJACK.cmake` file in `cmake/Modules`! To the best of my knowledge libopenshot has never had JACK support!) So, I'm just wondering what the status of the DeckLink "stuff" is, or if it's been so long since anyone's last tried it that none of us even knows.

**Comment by SuslikV** [comment]
Whom you asking? For example, I'm don't have this hardware, and I think that capturing is better with the OBS Studio (it has import for the BlackMagic devices too).

**Comment by ferdnyc** [comment]
> Whom you asking?

Anyone who has the answer, or any information at all about the DeckLink support in OpenShot really. I don't have the necessary hardware either, or I'd just try it myself. But in addition to the SDK (which I downloaded experimentally, an updated version anyway) you need appropriate driver libraries installed, it looks like, and that's as far as I got.

I'd like to modernize `FindBlackMagic.cmake` if it's still at all useful, but I don't want to waste my time on it if it's not needed or doesn't actually work.
