### ISSUE TITLE
Audio corruption at max amplitude

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/libopenshot#456]
When combined amplitude of mixed audio exceeds the maximum (1.0), clipping is the expected result. However, libopenshot appears to be doing something that corrupts the audio beyond simple clipping, with the values swinging around wildly instead of being hard-limited to 1.0. 

The effect can most easily be seen in this Audacity screenshot. (Lower waveform, with the upper being the same mix, but with the volume levels reduced in OpenShot):

![image](https://user-images.githubusercontent.com/538020/76172452-88573400-616c-11ea-82c4-3b2c1ec4bba6.png)

This has the effect of distorting the audio _beyond_ what would simply be heard from normal clipping, causing audible popping and crackling.

cc: @SuslikV , cc: OpenShot/openshot-qt#3256

**Comment by musteresel** [comment]
Is this happening at *every* time where clipping would be expected? (Might be related to the missing samples from some frames I'm currently working on)

**Comment by ferdnyc** [comment]
> Is this happening at _every_ time where clipping would be expected?

Near as I can _tell_, yes, and only when clipping would be expected. It seems like code that's meant to be constraining the amplitude to ±1.0, whenever it goes over/under, is instead making up unpredictable values other than ±1.0.

I don't _think_ it's any sort of **missing** data, per se, just because the distortions are so small. I mean, in that screenshot each labeled tickmark is just `0.005` seconds apart. If data were missing, I'd expect it to be in larger chunks than that.

**Comment by SuslikV** [comment]
There is screenshot at higher zoom:
https://github.com/OpenShot/openshot-qt/issues/3256#issuecomment-599053363

original issue is seems to be this: https://github.com/OpenShot/openshot-qt/issues/1069 so, it is long time issue.

I can look at this (no time deadlines), but if you have better skills...

**Comment by ferdnyc** [comment]
@SuslikV 

If you're able to take a look at it, that would be great, thanks! It'd be a few days at least before I'd be able to get to it.

I made the mistake of discovering a [new tool (`clazy`)](https://github.com/KDE/clazy) for scanning and checking Qt code, and after about 12 hours I've got it running on the libopenshot codebase with no warning messages at all. (Except for the couple I turned off, because like _all_ of our polymorphic classes are copyable and we'll just have to live with that.)

But it pointed me at a ton of improvements in the way data is passed around the code. (Mostly by becoming a [`const` nazi](http://gamesfromwithin.com/the-const-nazi).) And along the way I ended up writing a new class (ChunkPath) to consolidate the parts of ChunkReader and ChunkWriter that were copy-pased into both of them, I fixed the deprecation warnings Qt and Zmq were emitting, and I eliminated all of the C-style `sleep()` and `usleep()` calls in the code.

So I've got branches upon branches I need to submit today.

**Comment by musteresel** [comment]
The issue is most likely in `Timeline::GetFrame()` right? I'm currently working on rewriting that code, give me a few days (max) because that might solve the issue.

**Comment by musteresel** [comment]
OT: @ferdnyc Regarding `const`: Have you seen my message in zulip? Some of the changes only add noise (`const` for a parameter in a member function *declaration*; that `const` needs to be at the definition)

**Comment by ferdnyc** [comment]
@musteresel 
> OT: @ferdnyc Regarding `const`: Have you seen my message in zulip?
I don't know what that is. (I've probably been told, but I'm old and set in my ways.)

> Some of the changes only add noise (`const` for a parameter in a member function _declaration_; that `const` needs to be at the definition)
> 
> ```
> struct Foo {
>   void frob(const Bar baz) const;
>    //         ^ no; useless   ^ yes; very good
> };
> ```

The advice clazy dispenses is somewhat more targeted — for any complex class being passed around, if it's not modified, it gets changed to be passed by reference -- so, not of either of those, but...

 ```
struct Foo {
  void frob(const Bar& baz);
};

Saving the 40, 50, 96 bytes per parameter spent on copying the object. (It even points out the size of the object when it's scanning.)

AIUI OpenMP will make copies itself when spawning threads, so it should still be thread-safe. But I need to run a lot of tests to confirm that. So far I've only exercised the modified code with the unit tests, which still pass, but as you know they're far from complete. 

So before I submit any of _these_ changes, I'll probably write some more, to beef up our coverage across other parts of the code. (First target: ZmqLogger.)

**Comment by SuslikV** [comment]
@musteresel 
> The issue is most likely in `Timeline::GetFrame()` right?..

No. It's more likely in JUCE usage and its internal math features.

**Comment by SuslikV** [comment]
https://github.com/OpenShot/libopenshot/blob/816118b6f62743142839b9a73631b7a9d7518a4e/src/FFmpegWriter.cpp#L1502

https://github.com/OpenShot/libopenshot/blob/816118b6f62743142839b9a73631b7a9d7518a4e/src/FFmpegWriter.cpp#L1528-L1531

 :mag: :man_facepalming:
JUCE uses _float_ for buffer and can use _double_ for its own math and everything is spoiled by _libopenshot_ writing procedures. Of course, in this code (1.0 ; -0.1) is absolute max and even [1.0; -1.0] not accepted. This may resolve mystery behind this comment:

https://github.com/OpenShot/libopenshot/blob/816118b6f62743142839b9a73631b7a9d7518a4e/src/FFmpegReader.cpp#L1630-L1632

**Comment by ferdnyc** [comment]
I have been wondering why we _aren't_ using JUCE for the audio sample conversion. It has the <code>AudioBuffer<<var>type</var>></code> class for representing arrays of samples (even interleaved multichannel), with `getReadPointer()` and `getWritePointer()` methods to return `AudioPointer<>` objects for walking the sample values. But actually walking the values isn't even necessary, in many cases, because <code>AudioPointer<>::convertSamples(<var>OtherPointer</var>, <var>count</var>)</code> "Writes a stream of samples into this pointer from another pointer."

The documentation for all these classes is at [juce_audio_basics/buffers](https://docs.juce.com/master/group__juce__audio__basics-buffers.html), and on the JUCE forum one of the developers pointed to [this example code](https://github.com/WeAreROLI/JUCE/blob/b86b95b98037d5265c212c1e95dfa3017e634333/modules/juce_audio_devices/native/juce_android_OpenSL.cpp#L171):
```c++
static void convertFromOpenSL (const int16* srcInterleaved, AudioBuffer<float>& audioBuffer)
    {
        for (int i = 0; i < audioBuffer.getNumChannels(); ++i)
        {
            typedef AudioData::Pointer<AudioData::Float32,
                AudioData::NativeEndian, AudioData::NonInterleaved, AudioData::NonConst>
            DstSampleType;

            typedef AudioData::Pointer<AudioData::Int16,
                AudioData::LittleEndian, AudioData::Interleaved, AudioData::Const>
            SrcSampleType;

            DstSampleType dstData (audioBuffer.getWritePointer (i));
            SrcSampleType srcData (srcInterleaved + i, audioBuffer.getNumChannels());
            dstData.convertSamples (srcData, audioBuffer.getNumSamples());
        }
    }
```

**Comment by ferdnyc** [comment]
(There are also methods to apply both linear gain and gain ramps to one or all channels in a buffer, to copy or add a channel from a different buffer with and without gain ramps, and to reverse all or part of an entire buffer or an individual channel.)

**Comment by SuslikV** [comment]
> I have been wondering why we _aren't_ using JUCE for the audio sample conversion...

You know the answer:
> So unless there's some reason why that'll cause _undesirable_ behavior, that's the way it should be coded. "They're the same, it doesn't matter" isn't a good enough reason to do it differently. If they **are** the same, then there's no reason to break with the established coding style.

Coding style.
