### ISSUE TITLE
Symbols not found for architecture x86_64 on Mac OS

### ISSUE THREAD

**Issue by fitzmode** [OpenShot/libopenshot#465]
Firstly my apologies if this is just an error with my environment. Kind of new the C/C++. 
After running `make` in `libopenshot/build` , the build fails while linking `libopenshot.dylib`.

I'm also working on documenting notes on any issues I've had to work through on MacOS since the build steps are are currently outdated to hopefully help future contributors.

  ```
fitzmode$: make

[2%] Linking CXX shared library libopenshot.dylib

Undefined symbols for architecture x86_64:
  "juce::this_will_fail_to_link_if_some_of_your_compile_units_are_built_in_release_mode::this_will_fail_to_link_if_some_of_your_compile_units_are_built_in_release_mode()", referenced from:
      ___cxx_global_var_init in mocs_compilation.cpp.o
      ___cxx_global_var_init in AudioBufferSource.cpp.o
      ___cxx_global_var_init in AudioReaderSource.cpp.o
      ___cxx_global_var_init in AudioResampler.cpp.o
      ___cxx_global_var_init in CacheBase.cpp.o
      ___cxx_global_var_init in CacheDisk.cpp.o
      ___cxx_global_var_init in CacheMemory.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libopenshot.0.2.5.dylib] Error 1
make[1]: *** [src/CMakeFiles/openshot.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ferdnyc** [comment]
@fitzmode 

Most likely that's coming from the files that `#include "JuceHeader.h"` from libopenshot, and for the reasons indicated:
> this_will_fail_to_link_if_some_of_your_compile_units_are_built_in_release_mode

That symbol is embedded into debug builds of the JUCE code, to prevent linking them with release builds of code that depends on them.

So, most likely, your libopenshot-audio build was done in Debug mode, but your libopenshot build in Release mode.

Depending whether you want a debug or release build, you should either:
1. Rebuild libopenshot-audio in Release mode
    ```sh
    cd /path/to/libopenshot-audio/build
    make clean
    cmake -DCMAKE_BUILD_TYPE=Release .
    make
    ```
1. Or, rebuild libopenshot in Debug mode
    ```sh
    cd /path/to/libopenshot/build
    make clean
    cmake -DCMAKE_BUILD_TYPE=Debug .
    make
    ```

**Comment by ferdnyc** [comment]
No updates on this, so I'm going to close it as answered. I'm pretty confident the issue was as I described, I've hit that plenty of times myself. It's an intentional sanity-check measure built into the JUCE code.

Feel free to reopen if changing the build type didn't solve the issue!
