### ISSUE TITLE
Code improvements results from Cppcheck

### ISSUE THREAD

**Issue by jensdenbraber** [OpenShot/libopenshot#487]
I ran [cppcheck](https://github.com/danmar/cppcheck) on the libopenshot codebase which resulted in the some code improvements. 

Download the results here: [libopenshot_cppcheck.zip](https://github.com/OpenShot/libopenshot/files/4398956/libopenshot_cppcheck.zip)

**Comment by ferdnyc** [comment]
@jensdenbraber Thanks, I've been doing more static analysis of libopenshot myself recently, mostly using online tools, but somehow never thought to try cppcheck.

The XML format is pretty impenetrable without the tool itself, so I ran `cppcheck-htmlreport` to convert it to the attached pair of HTML files and a CSS stylesheet, for the benefit of any other project members who may want to explore the results.

[libopenshot-cppcheck.zip](https://github.com/OpenShot/libopenshot/files/4400607/libopenshot-cppcheck.zip)

Like any static analysis, there's a fair degree of noise, but it does catch a few things worth investigating. PRs welcome!
