### ISSUE TITLE
HEIC image support.

### ISSUE THREAD

**Issue by AndreOe** [OpenShot/libopenshot#488]
Hi all,

i am trying to import an image in Apples HEIC format. Unfortunately it fails.
I think ImageMagick supports HEIC format with libheif.
I tried to compile openshot and add the support, with no success.
Could you check and if possible add import for HEIC files?
Thank you!

**Comment by jeffski** [comment]
My understanding is that the image will be handled by the Qt library and not by ImageMagick. I am not sure if Qt supports HEIC, it is not listed here: https://doc.qt.io/qt-5/qtimageformats-index.html.

Is it possible to handle the conversion from HEIC to jpg or png before importing in to libopenshot/OpenShot?

**Comment by AndreOe** [comment]
Sure i can convert to jpg before importing. 
Still i think it should be possible to directly import in the original heic format via ImageMagick.
I think the Clip.cpp is never using ImageReader.cpp to read files.
When adapting the code to do so it opens the heic file but the color is wrong.

**Comment by mwlsn76** [comment]
Can HEIC compatability be added?
