### ISSUE TITLE
FFmpegWriter loses SAR (sample aspect ratio) on output videos

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/libopenshot#489]
While looking into OpenShot/openshot-qt#3329 some, I decided to export the test video I had set up with the "NTSC 23.98 fps" profile, which is the one with this definition:

```
description=NTSC 23.98 fps
frame_rate_num=24000
frame_rate_den=1001
width=720
height=486
progressive=1
sample_aspect_num=8
sample_aspect_den=9
display_aspect_num=4
display_aspect_den=3
colorspace=601
```

However, when I exported the video, I was surprised to discover that despite the Aspect Ratio being set to 4:3 and the Pixel Ratio being set to 8:9 (confirmed on the Advanced / Profile tab), the resulting video detected differently in both VLC and MediaInfo:
```
$ mediainfo -Full /var/tmp/aspect.mp4|egrep -i '(width|height| ratio )'
Width                                    : 720
Width                                    : 720 pixels
Height                                   : 486
Height                                   : 486 pixels
Stored_Height                            : 496
Sampled_Width                            : 720
Sampled_Height                           : 486
Pixel aspect ratio                       : 1.000
Display aspect ratio                     : 1.481
Display aspect ratio                     : 3:2
```

Looking through the code, I noticed that while the `pixel_ratio` Fraction is passed in to `SetVideoOptions()`, after that:

* It's stored in `info.pixel_ratio` (as `.num` and `.den`)
    https://github.com/OpenShot/libopenshot/blob/166f69389b6d8a601b51e8d559c418f56a144bba/src/FFmpegWriter.cpp#L248-L254

* It's used to compute `info.display_ratio` from the `width` and `height`:
    https://github.com/OpenShot/libopenshot/blob/166f69389b6d8a601b51e8d559c418f56a144bba/src/FFmpegWriter.cpp#L264-L272

...And then it's _**never used again**_. Nor is `display_ratio`! Neither of them are ever even accessed. Neither one is supplied to any FFmpeg context. In fact, other than setting the `AVCodecContext` `width` and `height`:
https://github.com/OpenShot/libopenshot/blob/166f69389b6d8a601b51e8d559c418f56a144bba/src/FFmpegWriter.cpp#L1207-L1210
...there's nothing further in the code that sets the output sizing or attempts to define the `sample_aspect_ratio` of any of the output contexts.

Meanwhile, if I rip DVD content _from_ a 4:3 NTSC DVD, the results are different: 
```sh
$ # First converting to AVI, because `ffprobe` can't directly examine .VOB files
$ cat VTS*.VOB | ffmpeg -i - -s 720x576 -c:v mpeg4 -c:a mp3 -y VTS.avi

$ # Now, the same MediaInfo command I ran on the OpenShot output file above
$ mediainfo -Full VTS.avi|egrep -i '(width|height| ratio )'
Width                                    : 720
Width                                    : 720 pixels
Height                                   : 576
Height                                   : 576 pixels
Sampled_Width                            : 720
Sampled_Height                           : 576
Pixel aspect ratio                       : 1.067
Display aspect ratio                     : 1.333
Display aspect ratio                     : 4:3

$ # And ffprobe also shows a SAR that isn't 1:1...
$ ffprobe -hide_banner -i VTS.avi            
Input #0, avi, from 'VTS.avi':
  Metadata:
    encoder         : Lavf58.29.100
  Duration: 00:08:34.91, start: 0.000000, bitrate: 598 kb/s
    Stream #0:0: Video: mpeg4 (Simple Profile) (FMP4 / 0x34504D46), yuv420p,
 720x576 [SAR 16:15 DAR 4:3], 456 kb/s, 29.97 fps, 29.97 tbr, 29.97 tbn, 30k tbc
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 128 kb/s
```
As a result, when I play the `VTS.avi` file in VLC, it automatically formats itself to 4:3 aspect — switching from "Default" to "4:3" has no discernible effect. However, if I play that `aspect.mp4` test export from OpenShot, switching to "4:3" _does_ change the size, because the "Default" presentation is not correctly sized due to the false 1:1 pixel ratio.

Don't we need to be using the `info.pixel_ratio` to set `sample_aspect_ratio` on the output context, when writing videos with non-uniform pixel ratios?

cc: @jonoomph @eisneinechse @SuslikV

**Comment by SuslikV** [comment]
I prefer to use square pixels and never looked into the none square ones. Maybe you are right.

**Comment by MattLathropTL** [comment]
I can confirm SAR is not maintained. I have been resampling each frame to square pixels and changing the resolution of the videos to accommodate in my software.

**Comment by hgerry** [comment]
Just to say that I would also really appreciate a fix for this as I am coming across the same issue when processing some miniDV footage. I do love this software overall, thanks all for your work.
