### ISSUE TITLE
AV_GET_CODEC_TYPE() points to different enum types. Drop support for FFmpeg below 0.8 and below

### ISSUE THREAD

**Issue by SuslikV** [OpenShot/libopenshot#490]
The AV_GET_CODEC_TYPE() returns `codec_type` field that itself has different types depending on FFmpeg version

Compare types of the `codec_type` field:
https://ffmpeg.org/doxygen/0.5/structAVCodecContext.html
vs
https://ffmpeg.org/doxygen/1.0/structAVCodecContext.html

This also has workaround in the code, that doesn't uses AV_GET_CODEC_TYPE() call at all (stream not in use here):
https://github.com/OpenShot/libopenshot/blob/166f69389b6d8a601b51e8d559c418f56a144bba/src/FFmpegWriter.cpp#L1074-L1078

https://github.com/OpenShot/libopenshot/blob/166f69389b6d8a601b51e8d559c418f56a144bba/src/FFmpegWriter.cpp#L1157-L1161

and next part of the code missing this version check:
here the `AVMEDIA_TYPE_AUDIO` can be `CODEC_TYPE_AUDIO` and vise versa.
https://github.com/OpenShot/libopenshot/blob/166f69389b6d8a601b51e8d559c418f56a144bba/src/FFmpegWriter.cpp#L798-L804

If FFmpeg below 0.8 isn't supported then some checks can be omitted.
Similar to already  proposed changes: https://github.com/OpenShot/libopenshot/pull/455

**Comment by ferdnyc** [comment]
\*nod* As you note, #455 already takes care of removing these, along with a bunch of other ancient code paths. Though, yeah, the fact that ffmpeg with `CODEC_TYPE_VIDEO` would still break **anyway** when it got to line 799 is even more reason to lose that code.

(I wonder if I can drop any of `FFmpegUtilities.h` also, though? Hmmm...)

**Comment by SuslikV** [comment]
See no moves into resolving this.
