### ISSUE TITLE
[IDEA] Automated multitrack sync

### ISSUE THREAD

**Issue by forart** [OpenShot/libopenshot#494]
Hi there, I recently discovered a very cool lib called [Aurio](https://github.com/protyposis/Aurio) "that focuses on audio processing, analysis, media synchronization and media retrieval and implements various audio fingerprinting methods".

As [this video](https://www.youtube.com/watch?v=QXQVPXjR3Lc) demonstrates, it's able - through its GUI called [AudioAlign](https://github.com/protyposis/AudioAlign) - to analyze and align audios between many (video) tracks.

The only drawback is that it has been developed in C# for .NET, so it's Windows-only.

It would be really great to establish some kind of collaboration between projects in order to (finally) obtain a platform-indipendent open source a/v synchronizer.

Hope that inspires.

Note: I'm pushing this to other projects too...

**Comment by SuslikV** [comment]
This has nothing to do with openshot itself.

**Comment by forart** [comment]
No?
Isn't OpenShot an NLE ?
