### ISSUE TITLE
Problem building libopenshot with latest ffmpeg

### ISSUE THREAD

**Issue by wittenbe** [OpenShot/libopenshot#5]
Compiling libopenshot with newest ffmpeg installed yield the following error:

```
FFmpegReader.h:160:91: error: ‘PixelFormat’ has not been declared
   void convert_image(long int current_frame, AVPicture *copyFrame, int width, int height, PixelFormat pix_fmt);
```

and other similar errors. Apparently PixelFormat was renamed to AVPixelFormat, but adjusting the affected files in openshot just leads to other errors (other changes?)

**Comment by scott--** [comment]
I do not know if you still have this issue, but I got libopenshot to compile by adding the following hack to the bottom of FFmpegUtilities.h

```c
  #define PixelFormat AVPixelFormat
  #define PIX_FMT_RGBA AV_PIX_FMT_RGBA
  #define PIX_FMT_NONE AV_PIX_FMT_NONE
  #define PIX_FMT_RGB24 AV_PIX_FMT_RGB24
  #define PIX_FMT_YUV420P AV_PIX_FMT_YUV420P
```

**Comment by jonoomph** [comment]
Thanks for the heads up. I'll take a look. =)
-Jonathan

On Wed, Nov 11, 2015 at 10:32 PM, scott-- <notifications@github.com> wrote:

> I do not know if you still have this issue, but I got libopenshot to
> compile by adding the following hack to the bottom of FFmpegUtilities.h
>
>   #define PixelFormat AVPixelFormat
>   #define PIX_FMT_RGBA AV_PIX_FMT_RGBA
>   #define PIX_FMT_NONE AV_PIX_FMT_NONE
>   #define PIX_FMT_RGB24 AV_PIX_FMT_RGB24
>   #define PIX_FMT_YUV420P AV_PIX_FMT_YUV420P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenShot/libopenshot/issues/5#issuecomment-155994920>.
>



-- 
*-Jonathan Thomas*
OpenShot Studios, LLC
www.openshotstudios.com
