### ISSUE TITLE
General Question realted to FFmpeg lib and rendering

### ISSUE THREAD

**Issue by Nirmal1313** [OpenShot/libopenshot#508]
hi,

if I have two videos that can play parallel in the open shot. if I wanna understand the logic behind that mechanism which CPP file I need to start to looking or making notes from that?

**Comment by SuslikV** [comment]
`src/Timeline.cpp` has logic for frames composition (add_layer) where new frame created from many and  new audio added to the frame. Player then playbacks this "final" image. FFmpeg only used to get uncompressed frames in RGB format from each video. Audio processed the same way.
