### ISSUE TITLE
Tests fail on !x86 architectures

### ISSUE THREAD

**Issue by ghisvail** [OpenShot/libopenshot#51]
I managed to upload `libopenshot` and `libopenshot-audio` to Debian. However, only x86 architectures have had successful builds of `libopenshot` so far (see [log](https://buildd.debian.org/status/logs.php?pkg=libopenshot&ver=0.1.2%2Bds1-3)). All other supported architectures, such as the `arm` or `mips` families, fail to pass certain tests.

**Comment by jonoomph** [comment]
I'm not sure what I need to do to address this. arm and mips are not my target architectures, so it doesn't really bother me at the moment. Contributions welcome, if it's something easy to tweak.

**Comment by ferdnyc** [comment]
Hmm. I don't quite get why the merge of #339 didn't auto-close this, but anyway it should be fixed now (except on PowerPC 64 LE, which is still wayyyyy messed-up for unknown reasons), so closing.
