### ISSUE TITLE
Build Success ,but crash in PyUnicode_FromFormat.

### ISSUE THREAD

**Issue by royaldragon** [OpenShot/libopenshot#52]
I want to  build libopenshot by myself.  According to the building guide in InstallationGuide.pdf, I download the latest code and succeed to build a libopenshot.so and libopsnshot-audio.so in my Ubuntu 14.04.  But when I try to run launch.py of openshot-qt,  it crashed. After some debuging effort ,I found that the software crashed when calling PyUnicode_FromFormat function in libsip. I have no idea about how to solve this problem.

When I building libopenshot.so, I found that I can't just use python pip and apt-get to install all the dependencies packages, because the latest version pyQt5(for example 5.7.1) remove some functions that openshot-qt needed. So I have to build pyQt5 and sip by myself. My build environment is:

Ubuntu 14.04
Python:  3.5.2
pyQt5:  5.5.1
sip:  4.18.1

The other dependencies are installed by apt-get or pip install .

Anyone knows how to solve this problem,? Or which version of dependencies packages should I use?

**Comment by royaldragon** [comment]
I find a way to solve this problem,  install python35-dev and it works. But After rebuild pyQt5,  the launch.py still crash in the QApplication.__init__(self, *args) function. It seems that the problem is in the pyQt5. Am I use a wrong version of pyQt5 ?

**Comment by komackaj** [comment]
Hi, I have no problem to build libopenshot from latest master (57dc7bc) using Debian Stretch with:
- python 3.5 
- Qt 5.8 (and I think was able to build with Qt 5.7 on Debian Jessie) 
- python3-pyqt5 5.7
using only system packages (without pip). Build for Ubuntu 14.04 with system packages only should be no problem - see packages in [Openshot's official PPA](http://openshot.org/ppa/).

Have you followed instructions as in [build docs](https://docs.google.com/document/d/1V6nq-IuS9zxqO1-OSt8iTS_cw_HMCpsUNofHLYtUNjM/pub#h.zifhywubw33b)? Are you using system Qt5 libraries, unofficial PPA or local builds (e.g. installed by QtCreator) - according to [official Ubuntu PPA](https://launchpad.net/ubuntu/trusty/+package/python3-pyqt5) only Qt 5.2 is available by default.

> I found that I can't just use python pip and apt-get to install all the dependencies packages, because the latest version pyQt5(for example 5.7.1) remove some functions that openshot-qt needed.

Could you post error messages from your build or what went wrong? Did `openshot-audio-test-sound` for libopenshot-audio, and `make test` and `python3 -c 'import openshot'` passed for you after appropriate `sudo make install`?
