### ISSUE TITLE
Player Demo Does not play video seamless.

### ISSUE THREAD

**Issue by nishisahlot** [OpenShot/libopenshot#523]
First of all thank you to all developers who build this amazing library. I build the library recently on my ubuntu and played the simple mp4 file but PlayerDemo class does not play video seamless. Video plays with some glitch.

Strange thing is when i play video in openshot-qt it plays smoothly. But openshot-qt internally uses libopenshot.

Can someone help me and tell why libopenshot playerdemo does not play video smoothly

**Comment by nishisahlot** [comment]
I forgot to provide max width and height in settings. Now it plays correctly.

**Comment by ferdnyc** [comment]
@nishisahlot Glad to hear you got it sorted out! The demo code originally predates the Settings class by a _lot_, and it's very likely we haven't sufficiently updated it to account for libopenshot API evolution. If there are any changes you think would be beneficial for new developers working with libopenshot, by all means please submit a PR!
