### ISSUE TITLE
Output video does not match input

### ISSUE THREAD

**Issue by jeffski** [OpenShot/libopenshot#531]
I've noticed a strange issue where frames from of a source video seem to freeze towards the end when written to an output video.

This is the input file: https://shillitto.s3-ap-southeast-2.amazonaws.com/openshot/length/input.mp4

And this is the output file: https://shillitto.s3-ap-southeast-2.amazonaws.com/openshot/length/output.mp4

The input should have an animation that starts from black and should end in white.

The output animation appears to play about 3/4's of the way through before stopping and showing the same frame to the end.

I used the following code:

```
Clip clip1(new FFmpegReader("input.mp4"));
clip1.Position(0.0);
clip1.Layer(1);
clip1.Start(0.0);
clip1.End(1.10);

Timeline timeline(1920, 1080, Fraction(25,1), 44100, 2, LAYOUT_STEREO);
timeline.AddClip(&clip1);
timeline.Open();

FFmpegWriter writer("output.mp4");
writer.SetAudioOptions(true, "aac", 44100, 2, LAYOUT_STEREO, 128000);
writer.SetVideoOptions(true, "libx264", Fraction(25, 1), 1920, 1080, Fraction(1,1), false, false, 0);
writer.PrepareStreams();
writer.SetOption(VIDEO_STREAM, "crf", "23" );
writer.WriteHeader();
writer.Open();
writer.WriteFrame(&timeline, 0, clip1.Duration() * 25);

writer.Close();
timeline.Close();
```

Something I noticed was that when I play the source video using VLC player on Ubuntu something very similar happens in the player. When I play using the built in Ubuntu Video player, VLC on Windows, Windows 10 Player or Windows Media Player it appears fine. The output 'bakes' in the issue.

I am not sure if maybe this is an FFMpeg issue on my version of Ubuntu. It would be good to know if anyone can reproduce the issue or have any ideas on how I need to configure my FFMpeg install on Ubuntu.

**Comment by jeffski** [comment]
Could it be the reader isn't reading the last few frames or the writer not writing?

**Comment by MattLathropTL** [comment]
I am seeing this as well. It occurs both with the library and with the released version of openshot. I can see the issue in the loaded files in premier as well as VLC

**Comment by MattLathropTL** [comment]
@jeffski Did you ever find a workaround for this? I have isolated it to the Reader (the error I posted above seems unrelated). This seems to happen on all MP4 H.264 videos I've tried but does not happen on ProRes. @jonoomph Any ideas?

**Comment by jeffski** [comment]
@MattLathropTL my only workaround was to add extra frames to the source video, i.e. in the example above, an extra half second of black at the start and half a sec of white at the end. It works for my use case but if I need 100% frame accuracy in the future that might not be possible.

**Comment by MattLathropTL** [comment]
> @MattLathropTL my only workaround was to add extra frames to the source video, i.e. in the example above, an extra half second of black at the start and half a sec of white at the end. It works for my use case but if I need 100% frame accuracy in the future that might not be possible.

Dang that’s not an option for me as I’m working on implementing this into another program and I can’t exactly just tell the users to add frames to the video. I’ve been trying to dive in and figure it out but I don’t have enough ffmpeg experience. I’m trying to upgrade to a more recent ffmpeg version to see if that fixes it.

**Comment by MattLathropTL** [comment]
Alright upgrading opencv didn't fix it, but I have localized the issue. It seems for the last few frames of video avcodec_receive_frame returns EAGAIN which causes libopenshot to send the next packet to it. The problem is that we run out of packets doing this and as best I can tell never send the NULL packet to try and flush those frames from the reader as described on [stackoverflow](https://stackoverflow.com/questions/57133098/ffmpeg-function-avcodec-receive-frame-always-return-eagain-error). I'm unsure of the implications of passing NULL to avcodec_send_packet when at the end of the stream. Anyone have any thoughts?

**Comment by MattLathropTL** [comment]
Ok I can get data from avcodec_receive_frame for the missing frames by passing in NULL to avcodec_send_packet. That said the packet no longer being valid for the associated frame messes up ProcessVideoPacket. GetAVFrame() also needs to be updated to potentially get multiple frames of video in one call. Would anyone have the time to help me implement these changes? I just don't know the code base well enough to know what all needs to be changed to accommodate this.

**Comment by jeffski** [comment]
This is becoming a noticeable issue again for some videos I'm creating with the last few frames not being rendered as expected. Any updates on this would b greatly appreciated.
