### ISSUE TITLE
How to correct audio pitch shift during fast forward 

### ISSUE THREAD

**Issue by nishisahlot** [OpenShot/libopenshot#536]
In Fast Forward like 2x 4x. The audio pitch is not correct. Please point me in right direction so i can fix this my self quickly. Your code is written very good and very well commented. You are really very experienced programmer I know you are busy but if you could point me out in right direction to correct audio pitch in fast forward then it will be really helpful and time saving.

**Comment by SuslikV** [comment]
Semitones not adjustable. The algorithm simply takes 1 audio frame that corresponds to the given video frame number. No other processing is made.
