### ISSUE TITLE
Undefined Symbols on Install MacOS x86_64

### ISSUE THREAD

**Issue by matthew-plusprogramming** [OpenShot/libopenshot#538]
I'm getting this error while trying to install the library on mac. Did I forget to install some sort of dependency?

```
[ 53%] Linking CXX shared library libopenshot.dylib
Undefined symbols for architecture x86_64:
  "juce::String::toStdString[abi:cxx11]() const", referenced from:
      openshot::Frame::Play()    in Frame.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [src/libopenshot.0.2.5.dylib] Error 1
make[1]: *** [src/CMakeFiles/openshot.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by matthew-plusprogramming** [comment]
@ferdnyc ever seen this error? I can't install the library with CMake...

**Comment by VinciXie** [comment]
[ 64%] Linking CXX shared library libopenshot.dylib
Undefined symbols for architecture x86_64:
  "__ZN6Magick12DrawableFontC1ERKSs", referenced from:
      __ZN8openshot10TextReader4OpenEv in TextReader.cpp.o
  "__ZN6Magick12DrawableTextC1EddRKSs", referenced from:
      __ZN8openshot10TextReader4OpenEv in TextReader.cpp.o
  "__ZN6Magick5ColorC1ERKSs", referenced from:
      __ZN8openshot10TextReader4OpenEv in TextReader.cpp.o
  "__ZN6Magick5Image4drawERKSt6vectorINS_8DrawableESaIS2_EE", referenced from:
      __ZN8openshot10TextReader4OpenEv in TextReader.cpp.o
  "__ZN6Magick5Image6magickERKSs", referenced from:
      __ZN8openshot11ImageWriter10WriteFrameESt10shared_ptrINS_5FrameEE in ImageWriter.cpp.o
  "__ZN6Magick5ImageC1ERKSs", referenced from:
      __ZN8openshot11ImageReader4OpenEv in ImageReader.cpp.o
  "__ZN6Magick5ImageC1EmmRKSsN10MagickCore11StorageTypeEPKv", referenced from:
      __ZN8openshot5Frame14GetMagickImageEv in Frame.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [src/libopenshot.0.2.5.dylib] Error 1
make[1]: *** [src/CMakeFiles/openshot.dir/all] Error 2
make: *** [all] Error 2

**Comment by ferdnyc** [comment]
The error @matthew-plusprogramming  was seeing (sorry, missed the tag at the time) looks like `libopenshot-audio` wasn't installed. That's the source of the `juce::` namespace symbols.

@VinciXie 's build errors would seem to indicate that libopenshot is configured with `HAVE_IMAGEMAGICK` when it's not actually available. It'd be helpful to see the full CMake output, the issue would be occurring during the configuration stage.

**Comment by ferdnyc** [comment]
(ImageMagick is totally optional, so there are two solutions to the problem: Either installing ImageMagick (and the Magick++ bindings for C++) and configuring libopenshot to link with it, or configuring it in CMake to build with ImageMagick disabled.)
