### ISSUE TITLE
will android support api make?

### ISSUE THREAD

**Issue by heaveninfosoft** [OpenShot/libopenshot#547]
will android support api make?

**Comment by ferdnyc** [comment]
@heaveninfosoft You're asking if libopenshot can be built for Android?

We've never tried, but I do not think so.

Both FFmpeg and QtWidgets are dependencies, most significantly, and while FFmpeg is probably available for Android, I do not believe QtWidgets is or will be. One of the major goals for QML and QtQuick is to support mobile interfaces in ways QtWidgets can't, and we don't currently have any way to build without QtWidgets.

PRs welcome! (You'd have to address the QtWidgets dependencies in the [`src/Qt`](https://github.com/OpenShot/libopenshot/tree/develop/src/Qt) — either by replacing them with QtQuick/QML equivalents, or removing them entirely.)
