### ISSUE TITLE
Text Overlay

### ISSUE THREAD

**Issue by bentaller-lion** [OpenShot/libopenshot#570]
Might want to add Text Overlay feature to let you put text on a video clip as a track.  This is a very common use case.  I am not sure how to implement it myself.  I am going through the code right now trying to figure out the best injection point.

**Comment by jeffski** [comment]
This is definitely possible. There are a few ways to create text clips (QtTextReader, TextReader and QtHtmlReader). The clips can then be added to a track above a video or image track.
