### ISSUE TITLE
MPEG Version 1 Layer 2 Sound Garbled

### ISSUE THREAD

**Issue by MattLathropTL** [OpenShot/libopenshot#572]
Hello! I have found a video file which seems to produce garbled audio in both openshot and openshotlib. Audio sounds fine in VLC, Adobe apps, etc. 

Here is a link to the video: https://www.dropbox.com/s/r5hj4kqr8u8hdzc/Xmas%2093%20-%20Part%201.mpeg?dl=0

Any ideas?

**Comment by Kaemmelot** [comment]
Same problem here. While the video seems fine, the sound is a shrieking mess.
In case it might help, for me it's a stereo mpga stream, 48 kHz, 192 kB/s, 32 bits per sample.

**Comment by jonoomph** [comment]
I'll give this a quick test...

**Comment by jonoomph** [comment]
Yup, it sounds like a hell demon is inside this video. Just based on listening to it, I hear the audio playing... mixed in with random sample values probably. For example, it sounds like the audio data might be padded or aligned in some way that OpenShot is not aware of, and thus, some uninitialized values are being mixed in. I'll continue to investigate.
