### ISSUE TITLE
Can we use libopenshot in Linux server?

### ISSUE THREAD

**Issue by nxtreaming** [OpenShot/libopenshot#575]
Can we use libopenshot in Ubuntu 18.04 LTS environment ( without GUI)?

Thanks.

**Comment by jeffski** [comment]
Yes, follow the instructions to install on Linux: https://github.com/OpenShot/libopenshot/wiki/Linux-Build-Instructions

One installed you need to include the library in your Python or C++ project. As you say there is no GUI.

**Comment by nxtreaming** [comment]
One more quesiton:

Does libopenshot depend on OpenGL for rendering? if so, we MUST provide a hardware-implementation OpenGL(such as NVIDIA T4 card)?

Thanks.

**Comment by jeffski** [comment]
Not as far as I know, CPU is the default. As far as I know extra setup is needed to run with hardware/OpenGL.

**Comment by nxtreaming** [comment]
Thanks a lot
