### ISSUE TITLE
failed to build openshot for windows a million times, trying to get an python binding?

### ISSUE THREAD

**Issue by hpp0hpp** [OpenShot/libopenshot#589]
Hi all,

I am a new python programmer, trying to using openshot python bidning to edit some video.

but after I followed the build instruction for a million times, it didn't work.

does any one have a built windows version openshot with python binding who can share?

or is there any work around for the python binding to a openshot I installed.

I have installed the openshot video editor on my windows , which works fine, but I just don't know how to use it in my python program.

Thank you all

**Comment by ferdnyc** [comment]
@hpp0hpp 

Building for Windows is... tricky. "it didn't work" isn't very specific. What sort of problems are you having?

The biggest problem with using pre-built bindings is that Python is _very_ picky about what it's willing to load, when it comes to compiled extensions. The note in the build instructions about needing to downgrade Python is no joke — unless you have the same Python build installed that the build servers used (MinGW64 Python 3.7.5), the Python module compiled from the SWIG-generated source code won't load. 

The module also won't load into any version of Python for Windows, which uses a different binary format.

If you _do_ have MinGW64 Python 3.7.5 installed (which involves downgrading from 3.8.6, forcing `pacman` to break a lot of dependencies along the way), then you actually can use the bindings from the OpenShot distribution. You just have to make one adjustment:

1. Navigate to `C:\Program Files\OpenShot Video Editor\lib`
1. Open the `library.zip` archive
1. Extract the `openshot.pyc` file into `C:\Program Files\OpenShot Video Editor\lib`. (You only need that one file, ignore the rest of the contents.)

With the `openshot.pyc` file extracted from the zip, you can import the bindings into MinGW64 Python 3.7.5. In a MinGW64 terminal (bash shell):
```sh
user@host MINGW64 ~
$ cd /c/Program\ Files/OpenShot\ Video\ Editor/

user@host MINGW64 /c/Program Files/OpenShot Video Editor
$ cd lib

user@host MINGW64 /c/Program Files/OpenShot Video Editor/lib
$ python3
Python 3.7.5 (default, Oct 17 2019, 08:08:02)  [GCC 9.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import openshot
>>> openshot.Version
OpenShotVersion('0.2.5-dev2')
```

**Comment by hpp0hpp** [comment]
@ferdnyc 
Hi , thank you for your kindly helping here.

for the prebuild version, if I downgrade to python 3.7.5, is that possible to use that directly on windows, or I have to use it in MINGW64 ? if so, maybe WSL2 will be a better choice for me.

I am just not quite understand why I can easily use released openshot binary directly with python QT, I think it's just a python binding for python-qt's ui callback functions, why it's so hard to have a non GUI python binding?

I just give up build it myself, casue when I solved bunch of issues, there are more problems to be solved, I am not professional programmer, maybe that is too hard for me.
