### ISSUE TITLE
caching/export problems (?)

### ISSUE THREAD

**Issue by RiedleroD** [OpenShot/libopenshot#617]
So I've recently started to use openshot to prepend an animation to my videos. The problem being that every time I export the video, roughly 0.2secs of sped-up video gets prepended to the video. My guess is that somehow the render cache from the preview is incorrectly used, but that's just a wild guess coming from the fact that when first opening the project, a cache of roughly that size is first rendered. My current project file consists of:
- a x264 1080p 30fps ~2s video that overlays over the main video
- a vp9 1080p 60fps ~2:30 video + audio
- a fadeout animation that lets the first video fade into the second

The bug occurs with at least vaapi+vp8 and vaapi-less vp8 and vp9, but only at 1080p. If I export at 480p or 720p it exports correctly. It doesn't occur with vaapi+x264 as far as I can see, though there's _something_ at the beginning of the video, it's way shorter and therefore less noticable.
I've currently worked around the problem by cutting the first 0.2sec of the video with ffmpeg, but it'd be nice if I wouldn't have to do that. I hope you can fix this.

**Comment by RiedleroD** [comment]
cmon wtf

**Comment by RiedleroD** [comment]
still a problem…

edit to avoid stale removal: yeah I stopped using openshot…

**Comment by JacksonRG** [comment]
Just tried testing this. No luck reproducing, as the vaapi wouldn't work for me.

I'll ask around for someone with the right hardware to render the test project I made

**Comment by RiedleroD** [comment]
For reference, I have an intel pentium N3710, according to neofetch.

edit: fuck it, it seems nobody cares. Openshot is shit anyway, so I already switched a loong time ago.
