### ISSUE TITLE
cmake could not find ImageMagick 7.x ?

### ISSUE THREAD

**Issue by kyrios123** [OpenShot/libopenshot#63]
Hello,

Is libopenshot still limited to ImageMagick 6.x ? If so is there any plan to support newer versions ?

Here is what I see when I build libopenshot 0.1.8:
```
Generating build files for openshot (0.1.8)
-- Could NOT find ImageMagick (missing:  ImageMagick_Magick++_LIBRARY ImageMagick_MagickWand_LIBRARY ImageMagick_MagickCore_LIBRARY) (found version "7.0.6-9")
```

Thanks !

**Comment by arekm** [comment]
It needs small patch to work with image magick 7.x:

http://git.pld-linux.org/gitweb.cgi?p=packages/libopenshot.git;a=blob_plain;f=imagemagick7.patch;hb=HEAD

but patching cmake detection wasn't necessary.

**Comment by Justinzobel** [comment]
Is it possible to get this merged into the actual libopenshot cmake as an option ie -DUSE_MAGICK7=ON

**Comment by kyrios123** [comment]
The patch can be applied successfully but it doesn't modify the cmake script which still report the same error at build time.

**Comment by arekm** [comment]
Do you have devel package for imagemagick? Because cmake detects imagemagick 7 just fine here - http://buildlogs.pld-linux.org/index.php?dist=th&arch=x86_64&ok=1&name=libopenshot&id=b5704619-42ca-4224-8c08-e306521e3374&action=text

**Comment by kyrios123** [comment]
Yes I do have the devel package for imagemagick:
* Line 23: imagemagick-devel is requested as build dependency
* Line 1596: patch is applied
* Line 1644: Could NOT find imagemagick

https://hastebin.com/azepijidof.coffeescript

**Comment by ferdnyc** [comment]
IM 7 support was added in #252.
