### ISSUE TITLE
rendered videos' audio does not import to iMovie

### ISSUE THREAD

**Issue by ckirmse** [OpenShot/libopenshot#634]
Using libopenshot, if I render out a video using FFmpegWriter with standard h.264 & aac streams, iMovie for some reason fails to import the audio stream. After a bunch of testing, it appears to be correlated with the audio stream not having a start time of 0. I found this code in FFmpegWriter.cpp around line 966-968

`
			// Since the PTS can change during encoding, set the value again.  This seems like a huge hack,

			// but it fixes lots of PTS related issues when I do this.

			pkt.pts = pkt.dts = write_audio_count;`

which dates from 2012 and as far as I can tell is not a good thing to be doing, from logging the values there. I removed the hack and it solved my problem; I think perhaps other audio bugs have been fixed over the years so this hack might now cause more harm than good? I'd love to know if there's any additional reasoning behind it.

**Comment by jeffski** [comment]
Interesting. I'm also seeing issues with QuickTime video previews which is also caused by the video start_time not being set to 0. Related ticket here: #644
