### ISSUE TITLE
Please add support for GPU accelerated video processing

### ISSUE THREAD

**Issue by rdeleonp** [OpenShot/libopenshot#66]
Please add support for GPU accelerated video processing.

**Comment by ferdnyc** [comment]
Done! Accelerated encoding and decoding are implemented in the current `develop` branch's HEAD. (Though there hasn't been an official release yet, that'll be along eventually as either 0.2.4 or 0.3.0, most likely.)

Also, not sure whether HW-accelerated encoding is working on Win/Mac yet. Both platforms' hw-accel preferences are disabled in OpenShot itself, for the moment, so accelerated processing is only available on Linux right now.
