### ISSUE TITLE
cmake fails on OpenShotAudio

### ISSUE THREAD

**Issue by fivenote** [OpenShot/libopenshot#669]
I'm building openshot on linux, following the build steps on [https://cdn.openshot.org/static/files/user-guide/developers.html](url).

I successfully built libopenshot-audio and installed to the dist folder as it says to do. When trying to build libopenshot I get the following on cmake. I checked all the dependent packages are installed. What's missing?

```
$ cmake -DLIBOPENSHOT_AUDIO_DIR=../../libopenshot-audio/build/dist ..
-----------------------------------------------------------------
          Welcome to the OpenShot Build System!

CMake will now check libopenshot's build dependencies and inform
you of any missing files or other issues.

For more information, please visit <http://www.openshot.org/>.
-----------------------------------------------------------------
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

Generating build files for OpenShot with CMake 3.16.3
  Building libopenshot (version 0.2.5)
  SO/API/ABI Version: 19

CMake Error at src/CMakeLists.txt:178 (find_package):
  By not providing "FindOpenShotAudio.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "OpenShotAudio", but CMake did not find one.

  Could not find a package configuration file provided by "OpenShotAudio"
  (requested version 0.2.0) with any of the following names:

    OpenShotAudioConfig.cmake
    openshotaudio-config.cmake

  Add the installation prefix of "OpenShotAudio" to CMAKE_PREFIX_PATH or set
  "OpenShotAudio_DIR" to a directory containing one of the above files.  If
  "OpenShotAudio" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/pi/src/openshot-git/libopenshot/build/CMakeFiles/CMakeOutput.log".
```

**Comment by ferdnyc** [comment]
@fivenote 

Sorry, the docs are slightly out of date. You should add `-DOpenShotAudio_ROOT=/path/to/libopenshot-audio/build/dist` (or the root of where you installed it, wherever that is) to the `cmake` command line for libipenshot.

**Comment by ferdnyc** [comment]
> @fivenote 
> 
> Sorry, the docs are slightly out of date. You should add `-DOpenShotAudio_ROOT=/path/to/libopenshot-audio/build/dist` (or the root of where you installed it, wherever that is) to the `cmake` command line for libipenshot.

(Or, if you install libopenshot-audio to a system prefix like `/usr` or `/usr/local`, then CMake should find the config automatically.)

**Comment by ferdnyc** [comment]
The `-DOpenShotAudio_ROOT` setting is **instead of** `LIBOPENSHOT_AUDIO_DIR`, there's no longer any need to set that.

**Comment by fivenote** [comment]
Awesome, thanks. Before I saw your reply, I found this works too...

cmake -DCMAKE_PREFIX_PATH=../../libopenshot-audio/build/dist ..

**Comment by nedcrow** [comment]
I haven't this how.
my tried command text is those
  cmake -DCMAKE_PREFIX_PATH=../../libopenshot-audio/build/dist ..
  cmake -DOpenShotAudio_ROOT=../../libopenshot-audio/build/dist ..
.
result log was same both two case.

    :~/libopenshot/build$ cmake -DCMAKE_PREFIX_PATH=../../libopenshot-audio/build/dist ..            
    ----------------------------------------------------------------- 
    Welcome to the OpenShot Build System!
    CMake will now check libopenshot's build dependencies and inform
    you of any missing files or other issues.                                                                                                                                                                                                       
    For more information, please visit <http://www.openshot.org/>. 
    -----------------------------------------------------------------                                                                                                                                                                               
    Generating build files for OpenShot with CMake 3.16.3 
      Building libopenshot (version 0.2.7) 
      SO/API/ABI Version: 21                                                                                                                                                                                                                        

    CMake Error at src/CMakeLists.txt:176 (find_package):
      By not providing  "FindOpenShotAudio.cmake" in CMAKE_MODULE_PATH this 
      project has asked CMake to find a package configuration file provided by
      "OpenShotAudio", but CMake did not find one.       
                                                                                                                                                                                            
    Could not find a package configuration file provided by "OpenShotAudio" 
    (requested version 0.2.0) with any of the following names:     
                                                                                                                                                                                   
       OpenShotAudioConfig.cmake
       openshotaudio-config.cmake                     
  
    Add the installation prefix of "OpenShotAudio" to CMAKE_PREFIX_PATH or set                                              
    "OpenShotAudio_DIR" to a directory containing one of the above files.  If  
    "OpenShotAudio" provides a separate development package or SDK, be sure it 
    has been installed.     

Obviously, this file(OpenShotAudioConfig.cmake) is in the path. how do that?
please help me.

**Comment by JacksonRG** [comment]
@fivenote when following [this](https://github.com/OpenShot/libopenshot/wiki/Linux-Build-Instructions) instructions page, does the audio demo make a sound?

**Comment by ferdnyc** [comment]
@nedcrow When you set the `CMAKE_PREFIX_PATH` (rather than `OpenShotAudio_ROOT`), you need to set it to the CMake directory within the install path.

So, if you built the audio library with `build/dist` as the install location, and installed it to there (meaning, you ran both `cmake --build build` **AND** `cmake --install build` after building it), the you should add `-DCMAKE_PREFIX_PATH=/path/to/libopenshot-audio/build/dist/lib/cmake` to your libopenshot `cmake` configure command.

I actually generally don't recommend using an _installed_ `libopenshot-audio` (unless it's installed to `/usr/` in which case the configuration is already in your default path and you shouldn't need to do anything). If you just want to _build_ with it, you can import it straight from its build tree.

Just run
```sh
cd /path/to/libopenshot-audio
cmake -B build -S .
cmake --build build
cd /path/to/libopenshot
cmake -B build -S . -DOpenShotAudio_ROOT=/path/to/libopenshot-audio/build
cmake --build build
```
(Setting `CMAKE_PREFIX_PATH` to `/path/to/libopenshot-audio/build` should also work.)

**Comment by ferdnyc** [comment]
Another handy CMake feature — if your builds use a _common_ install directory, and you've already installed a prerequisite, later builds will automatically pick it up from the install path.

For instance, if you know you're going to install everything to `/usr/local/`, you can:
```sh
# Build libopenshot-audio with `/usr/local` as the install prefix
cd /path/to/libopenshot-audio
cmake -B build -S . -DCMAKE_INSTALL_PREFIX=/usr/local
cmake --build build
cmake --install build # Installs config to /usr/local/lib/cmake

# Build libopenshot with same install prefix
cd /path/to/libopenshot
cmake -B build -S . -DCMAKE_INSTALL_PREFIX=/usr/local
# ^ Will automatically pick up OpenShotAudio config from /usr/local/lib/cmake/
cmake --build build
cmake --install build
```

**Comment by ferdnyc** [comment]
> @nedcrow When you set the `CMAKE_PREFIX_PATH` (rather than `OpenShotAudio_ROOT`), you need to set it to the CMake directory within the install path.

Actually, I think I'm wrong about that part, sorry.

My guess is, if `-DCMAKE_PREFIX_PATH=/path/to/libopenshot-audio/build/dist` didn't work, then the library probably hadn't been installed (`cmake --install build`) to that directory (`-DCMAKE_INSTALL_PREFIX=build/dist` when configuring, or `--prefix build/dist` added to the `cmake --install` command) after building it.

If that seems overcomplicated (it is), the simpler approach is to use the build directory, by setting `-DOpenShotAudio_ROOT=/path/to/libopenshot-audio/build`. That's still my recommendation. If building against an installed libopenshot-audio, the `CMAKE_INSTALL_PREFIX=` should be set to the same path for both library builds.

**Comment by ferdnyc** [comment]
Also, I've recently updated [the wiki page @JacksonRG linked to](https://github.com/OpenShot/libopenshot/wiki/Linux-Build-Instructions) with a couple of path corrections, and I've added/updated info on several missing or outdated dependencies.
