### ISSUE TITLE
Integrate the AMD Advanced Media Framework (AMF)

### ISSUE THREAD

**Issue by kphillisjr** [OpenShot/libopenshot#677]
The core of this request is to give AMD Graphics cards working hardware Accelerated encoding and decoding on windows. AMD has a public SDK with a license that is generally compatible with the license for OpenShot that is perfect for this task. Depending on hardware the Hardware Accelerated Decoder supports MPEG2, MPEG4, H264 H265 (HEVC), VP9, and AV1. The Hardware encoder ( depending on hardware) supports H264, and H265. In general the public repository for this library is part of the AMD GPU Open initiative ( See: https://github.com/GPUOpen-LibrariesAndSDKs/AMF ), and there is already working support for this library in OBS Studio ( see: https://github.com/obsproject/obs-amd-encoder )

**Comment by kerryhatcher** [comment]
I'd second this as a request. I'm stuck with NVIDIA at the moment but I would like to switch to AMD eventually due to their overall better Linux support. Unfortunately its just really hard to put hands on cards at the moment so I've got what I can get.
