### ISSUE TITLE
`libopenshot-audio` repository name in PDF has incorrect character

### ISSUE THREAD

**Issue by follower** [OpenShot/libopenshot#68]
I copy & pasted this from the `InstallationGuide.pdf` into Terminal.app:

    bzr branch lp:~openshot.code/libopenshot/libopenshot­audio

Unlike above (for me at least) it looks correct when pasted into terminal (with what appears to be a hyphen between `...shot` and `audio`).

However it results in an error message:

    bzr: ERROR: Invalid url supplied to transport: "bzr+ssh://bazaar.launchpad.net/~openshot.code/libopenshot/libopenshot%C2%ADaudio": no supported schemes

You'll notice that instead of a hyphen it has `%C2%AD`.

I verified the result via xxd:

```
$ pbpaste | xxd
0000000: 627a 7220 6272 616e 6368 206c 703a 7e6f  bzr branch lp:~o
0000010: 7065 6e73 686f 742e 636f 6465 2f6c 6962  penshot.code/lib
0000020: 6f70 656e 7368 6f74 2f6c 6962 6f70 656e  openshot/libopen
0000030: 7368 6f74 c2ad 6175 6469 6f              shot..audio
```

When I manually corrected the URL to have a hyphen it worked:

    bzr branch lp:~openshot.code/libopenshot/libopenshot-audio

I assume there's some "smart" hyphen-ing or something going on during the PDF production process.

(After further investigation it seems like it's a UTF-8 encoding of a "soft hypen" rather than a "hyphen minus".)

References:
 * <https://stackoverflow.com/questions/33152118/using-hyphen-in-the-url-without-encoding>
 * <http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=c2+ad&mode=bytes>
 * <https://listmaster.pepperfish.net/pipermail/netsurf-users-netsurf-browser.org/2009-March/008419.html>

**Comment by follower** [comment]
This may be the case for all hyphens in the PDF as I also encountered it with `brew install gcc48 --enable-all-languages`.

**Comment by ferdnyc** [comment]
The PDF docs are no longer current, the new docs are Markdown-based and hopefully won't have any similar encoding issues.
