### ISSUE TITLE
Missing transition files cause openshot::InvalidFile to be thrown, crash OpenShot

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/libopenshot#702]
While testing OpenShot/openshot-qt#4229, I discovered that if a project file is loaded that contains any invalid transition paths, libopenshot crashes OpenShot entirely.

This appears to be due to the relatively-new project file parsing code, as even fixing the paths in OpenShot's in-memory project `dict` doesn't prevent the crash (implying that the original data is still being read from disk).

Needless to say, a missing file shouldn't cause the application to completely crash.

I also notice there are no unit tests _at all_ for the `.osp` file loading, which is disturbing.

**Comment by ferdnyc** [comment]
I'm becoming more and more convinced, in light of this issue, that the transition files should actually live with _libopenshot_, not OpenShot itself. If libopenshot needs the transition files to operate properly, then it should own them, it shouldn't need to be pointed at an OpenShot installation just to not-crash when loading project data. That's completely ass-backwards.

The effects files, too, should really be part of libopenshot, since the effects are completely defined in its code. The fact that we have descriptions of, and icons for, them that only exist in an external repo is kind of crazy. OpenShot should be pulling those resources from the library's install, not the other way around.

**Comment by JacksonRG** [comment]
Ohh, I've been investigating a few crashes I've been having. This could explain some of those

**Comment by ferdnyc** [comment]
@JacksonRG I wouldn't be at all surprised. libopenshot's incredible fragility in the face of missing media files is a whole 'nother issue in its own right, we really need to address that.

_This_ issue certainly **exacerbates** it (or is exacerbated by it?), and the tetchiness it's displayed of late makes it all the more imperative that the library itself take ownership of all the files it requires. But, really it should just **never** _crash hard_, period. Not for something as silly as, "can't find an input file mentioned in the project JSON".
