### ISSUE TITLE
import openshot leads to segmentation fault

### ISSUE THREAD

**Issue by Kchour** [OpenShot/libopenshot#708]
After a successful build of both `libopenshot-audio` and `libopenshot`, I can't seem to get the python bindings to work:

```
kenny@kenny-Inspiron-7577:~/Development/misc/libopenshot/build$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openshot
Segmentation fault (core dumped)

```

**Comment by JacksonRG** [comment]
That's interesting. Do you have the most recent daily build of openshot?

**Comment by Kchour** [comment]
I think so? I cloned from the `develop` branch for both or whatever the default was

**Comment by JacksonRG** [comment]
Could you include what OS you're using?

Also, I assume you're using these instructions.
https://github.com/OpenShot/openshot-qt/wiki/Become-a-Developer

**Comment by Kchour** [comment]
Yeah my bad. I'm using ubuntu 18.04.

I went off of the instructions from here, but I believe they are nearly identical: 
[https://github.com/OpenShot/libopenshot/blob/develop/doc/INSTALL-LINUX.md](https://github.com/OpenShot/libopenshot/blob/develop/doc/INSTALL-LINUX.md)

...except for the extra `sudo ldconfig` at the end of instructions for building `libopenshot`. hmmmmm

**Comment by Kchour** [comment]
OK I think it works! The command `sudo ldconfig` in the link you mentioned helped!

Other than that, I think the instructions under `/doc` may be outdated

**Comment by JacksonRG** [comment]
Good to know, thanks. I'll take a look at those instructions and make sure they're up to date.
