### ISSUE TITLE
Brightness documentation is wrong, should be 1 to -1

### ISSUE THREAD

**Issue by jeffski** [OpenShot/libopenshot#71]
See: https://github.com/OpenShot/libopenshot/blob/7490aaa3e47ad9ccb7e40acb794c59640bafae05/include/effects/Brightness.h#L78

Values should be 1 to -1 instead of 100 to -100. RGB value is being multiplied by 255 so any number greater than 1 or -1 will just result in black or white pixels.

Alternatively you could update the calculation to divide by 100.

**Comment by ferdnyc** [comment]
Fixed, finally — so, _so_ belatedly.

> Alternatively you could update the calculation to divide by 100.

Naw, it was purely a documentation issue. The range isn't merely implemented as -1 – +1, it's defined that way in the introspection metadata for OpenShot:

https://github.com/OpenShot/libopenshot/blob/7490aaa3e47ad9ccb7e40acb794c59640bafae05/src/effects/Brightness.cpp#L188-L190

(Which means that the brightness range is truly -1 – +1, while the contrast range really is 0 – 100. Which is kind of nonsense, but oh well. ...It might actually be _less_ confusing than the fact that the metadata lists the contrast range as 0.0 – 100.0, yet the API documentation says "0 is invalid".)

**Comment by jeffski** [comment]
Thanks for clarifying and updating.
