### ISSUE TITLE
The output video is a little darker

### ISSUE THREAD

**Issue by tyzhkcad** [OpenShot/libopenshot#715]
The output video of libopenshot is a little darker than the input video， I think it is a bug.

**Comment by ferdnyc** [comment]
Closing this, as we can't really investigate without (at a MINIMUM):
1. Details about the operating system / version for the reported issue.
1. Information about the input video parameters (either the contents of the File Properties JSON tab, or MediaInfo profile).
1. Information about the output profile and/or preset selected.
