### ISSUE TITLE
Missing variables in Frame::DeepCopy

### ISSUE THREAD

**Issue by federicomassa** [OpenShot/libopenshot#73]
Hello everyone,
I am using libopenshot for a project, and I had some crashes when using Frame copy constructor (width and height were not set after copy). By looking at the sources I noticed that Frame::DeepCopy does not (in release 0.1.8) copy width and height parameters, which I think is a bug, because I imagine that DeepCopy should copy everything. I also noticed that other data members of Frame class are not instantiated, but I do not know if that is intentional (you should check that).
so I fixed if by simply adding (in Frame::DeepCopy)

```
width = other.width;
height = other.height;
```

**Comment by ferdnyc** [comment]
On this in particular, `Frame::DeepCopy()` was fixed some time ago, and as of #397 has unit tests to ensure that it's operating correctly. (Which uncovered a few more `DeepCopy()` bugs involving missing data members, as you mentioned at the end of this report.)
