### ISSUE TITLE
Scaling incorrect when using SCALE_NONE and scale_x / scale_y

### ISSUE THREAD

**Issue by jeffski** [OpenShot/libopenshot#754]
When using `SCALE_NONE` and then applying `scale_x` and/or `scale_y` it appears as if images and videos are scaled twice. For example an image that is 1000px x 500px with a scale of 0.5 will result in an image displaying in the rendered video at 250px x 125px, not 500px x 250px.

The code below demonstrates:

```
Clip clip1(new QtImageReader("wave-1000x500.jpg"));
clip1.Position(0);
clip1.Layer(1);
clip1.Start(0);
clip1.End(5);
clip1.scale = openshot::SCALE_NONE;

Clip clip2(new QtImageReader("wave-1000x500.jpg"));
clip2.Position(5);
clip2.Layer(1);
clip2.Start(0);
clip2.End(5);
clip2.scale = openshot::SCALE_NONE;
clip2.scale_x.AddPoint(0.5);
clip2.scale_y.AddPoint(0.5);

Timeline timeline(1280, 720, Fraction(25,1), 44100, 2, LAYOUT_STEREO);
timeline.AddClip(&clip1);
timeline.AddClip(&clip2);
timeline.Open();

FFmpegWriter writer("output.mp4");
writer.SetAudioOptions(true, "aac", 44100, 2, LAYOUT_STEREO, 128000);
writer.SetVideoOptions(true, "libx264", Fraction(25, 1), 1280, 720, Fraction(1,1), false, false, 0);
writer.PrepareStreams();
writer.SetOption(VIDEO_STREAM, "crf", "23" );
writer.WriteHeader();
writer.Open();
freopen("/dev/null", "w", stderr);
writer.WriteFrame(&timeline, 1, 10 * 25);

writer.Close();
timeline.Close();
```

This is the test image used (1000px x 500px)
[wave-1000x500.jpg](https://user-images.githubusercontent.com/1064199/136493599-ec1831c8-6c06-415f-86d6-7a836f8f9756.jpg)

The output video is here (1280px x 720px):
[output.mp4](https://user-images.githubusercontent.com/1064199/136493698-1ecb5bf1-e4c2-4ef2-8506-4537682c9cdb.mp4)

- The first clip renders at a size of 1000 x 500px as expected.
- The second clip renders at 1/4 the size at 250 x 125px - I would expect the video to be half the size of the original (scale: 0.5) at 500 x 250px

I have tested this with FFMpegReader and the issue is the same.

Somewhere the scale must be being run twice.

**Comment by JacksonRG** [comment]
@jeffski You might try setting scale to `best_fit`. I'm looking for an explanation for another user as to why the scale options are labeled as such, but under scale:none, changing the scale of one axis can affect the other.

**Comment by jeffski** [comment]
@JacksonRG I don't think that makes sense. If I scale the X axis, why would it scale the Y axis as well - unless you are maintaining aspect ratios. Scaling something by 50% should make it half the size, not quarter the size. Also this is a breaking change, it used to work as described. On upgrading to the latest version all our videos started rendering with elements smaller than they should be.

**Comment by jeffski** [comment]
Played about with this a bit more. It is definitely being scaled twice. If I comment out this code in QtImageReader.cpp (L249 - L257) then the image is scaled as expected to 50% of the original:

https://github.com/OpenShot/libopenshot/blob/111026d8a123090447e0a472b21ede38e7093bda/src/QtImageReader.cpp#L249-L257

This is for the QtImageReader which is easier to understand but something similar must be happening in the FFMpegReader too.

**Comment by jeffski** [comment]
Actually it doesn't seem correct with the code commented out. It does look like the image is scaled by 50% but the original image which is not scaled fills the viewport and the scaled image is 50% of that.

**Comment by alexzk1** [comment]
2 things look suspicious here:
co.Y at  float max_scale_x = parent->scale_x.GetMaxPoint().co.Y; 
shouldn't it be like co.X? if no - then just weird naming...
and second thing preview_ratio = t->preview_width / float(t->info.width);  is depend on X but used for X and Y while you try to scale separated. Maybe you need 2 separated ratios for X and Y.
