### ISSUE TITLE
Improve and adapt Windows build to use vcpkg

### ISSUE THREAD

**Issue by RichiCoder1** [OpenShot/libopenshot#76]
This is a terrific project, but currently it's quite a chore to setup and build on windows. I wanted to see if there would be any interest in improving the build DX by pulling depedent packages w/ VCPkg, as well as potentially setting up an AppVeyor CI (free)

**Comment by mlocati** [comment]
There's also https://github.com/OpenShot/libopenshot/issues/35 where I suggested to use MXE. I don't know how VCPkg compares to MXE

**Comment by RichiCoder1** [comment]
@mlocati Yup, I saw that one two. I'm honestly fine either way. VCPkg differs from MXE in that it's just a sort of dev-package specific package manager for cross platform C++ libraries to use on windows. Most every package that libopenshot depends on (except imagemagick, which could be swapped from graphicsmagick) is there, and it would allow of "simple" native windows builds. No custom installed environment, just straight windows.

MXE might technically be a simpler path, however, as I imagine it'd require much less work to adapt. I don't know what the CI story would be there though.

**Comment by ferdnyc** [comment]
How many package managers ARE there for Windows?!!? I don't think I've ever encountered the same one twice. Both of these are completely new to me, and don't match any of the like FIVE I already know about.

Such a tedious platform.

**Comment by mlocati** [comment]
@ferdnyc out of curiosity, which are the ones that you know?

**Comment by ferdnyc** [comment]
Chocolatey (used by AppVeyor), MSYS, MSYS2 (the OpenShot recommended dependency / build-tool chain, currently), NuGet... okay, maybe it's just four. (Now, six.)

**Comment by ferdnyc** [comment]
MSYS and MSYS2 aren't _quite_ "Windows package managers" in the traditional sense, admittedly. Nor is their grandpappy Cygwin, which I didn't even include.

**Comment by ferdnyc** [comment]
Going back to the OP, the addition of both FFmpeg 4 and ImageMagick 7 support in the libopenshot codebase over the past year means that building on Windows is now _much_ more of a realistic undertaking, thanks to nearly all of the dependencies being satisfiable using the current releases of various MSYS2 packages. 

The _only_ required tools and/or libs that can't be installed by just running `pacman` in the MSYS2 shell are, IIRC:
* `libopenshot-audio` (which is _itself_ buildable entirely with dependencies from `pacman`)
* `unittest++` (aka `unittest-cpp` in many package repos), for whatever odd reason. But that's a laughably simple "download the source, `configure`, `make`" sort of thing to build locally.

**Comment by ferdnyc** [comment]
And now that I've finally done the work to make UnitTest++ optional, in the libopenshot build (because you don't _have_ to run unit tests), that prospect becomes even less daunting.

I did take a look at MXE, on the strength of that other suggestion. It's just... _heavy_, and takes forever to compile the necessary dependencies on my Fedora box. I don't think I even got as far as _trying_ to compile any of our libraries. But any more on that would be more appropriate for #35 .
