### ISSUE TITLE
Not all frames are returned from the h264 decoder

### ISSUE THREAD

**Issue by Dykson** [OpenShot/libopenshot#789]
Hello.
I found that when transcoding, the last 8 frames are missing from my test file. They don't come back from the decoder. 
FFmpegReader.cpp line 925:
`
packet_error < 0
` makes the function
`frame_finished = getavframe();`  (955)
unavailable. Because of this, frames remain in the decoder that do not fall into the encoder.
[video for test](https://cloud.mail.ru/public/kyXi%2FtSQuSnT1K)
Tested on Debian 11.1 and libopenshot (develop - 91c47eb commit)

**Comment by jeffski** [comment]
Could it be related to this issue: https://github.com/OpenShot/libopenshot/issues/531

**Comment by Dykson** [comment]
> Может ли это быть связано с этой проблемой: [# 531](https://github.com/OpenShot/libopenshot/issues/531)

Yes, it's definitely the same problem. I can assume that this error will be repeated for any decoder. I was debugging the code FFmpegReader.cpp and after the end of the file, unused frames remain in the decoder and the last frame from the cache is duplicated. It just needs to be fixed.
