### ISSUE TITLE
New Feature : No API's for open shot to programatically create Videos with few existing video or image clips with random audio

### ISSUE THREAD

**Issue by Lakshmai** [OpenShot/libopenshot#824]
New Feature : No API's for open shot to programatically edit videos with the audio clip and video clips in segments or screenshots in segments with some random audio. Please let me know how to get involved here in this project to do some tweaks and user interface modifications to look much better.

**Comment by JacksonRG** [comment]
Hi @Lakshmai sorry for the wait. Currently we don't have a plan to automatically create slideshows like this. It's definitely an interesting idea, but our current focus is on improving Openshot's experience for the largest number of users.

As to your mention of getting involved, we have a guide here: https://github.com/OpenShot/openshot-qt/wiki/Become-a-Developer on getting started running our code from source on your computer. I'd be happy to help you if you have any problems there to get you started.
