### ISSUE TITLE
Hardware Acceleration / Low GPU Usage

### ISSUE THREAD

**Issue by senoalvrtsyan** [OpenShot/libopenshot#826]
Hi Openshot Team,

I'm using libopenshot with hardware acceleration, especially encoding (h264_nvenc), but I see almost no usage of GPU. Only some mb of GPU memory usage is visible and encoding with libx264 and h264_nvenc renders video on exact same times.

Can you advice how I can speed up the rendering time ?

**Comment by JacksonRG** [comment]
@senoalvrtsyan could you include any more info on your computer? For instance what OS, and GPU you're using?

**Comment by senoalvrtsyan** [comment]
Hi @JacksonRG , Laptop is Dell XPS 9500, which has NVIDIA GeForce GTX 1650 Ti Graphic Card and OS is ubuntu 20.04 LTS.

I also tested with NVIDIA Tesla T4 GPU(again using Ubuntu 20.04 LTS) and usage is exactly same. Openshot consumes only 1% of GPU and as a result I get same processing time with both CPU and GPU.

BTW: I'm using libopenshot in my program with `h264_nvenc` encoder (and do not use hw decoder, since it's still buggy)

**Comment by senoalvrtsyan** [comment]
Hi @JacksonRG 
Any new on this ?

**Comment by teito-dev** [comment]
Im facing this exact same issue im using VDPAU on linux for my nvidia gpu, and its loading a few Mbs into gpu memory, but never using the gpu to encode the video and after that just moving to cpu to render it full

@JacksonRG 
@jonoomph 

I'm on ubuntu linux 

```cpp
    openshot::Settings::Instance()->HARDWARE_DECODER = 6;
    openshot::Settings::Instance()->HW_DE_DEVICE_SET = 1;
    openshot::Settings::Instance()->HW_EN_DEVICE_SET = 0;
    
    openshot::Settings::Instance()->OMP_THREADS = 12;
    openshot::Settings::Instance()->DE_LIMIT_HEIGHT_MAX = 1100;
    openshot::Settings::Instance()->DE_LIMIT_WIDTH_MAX = 1950;

   Then im using the following options when exporting the video
           if (useGpu) {
            writer.SetVideoOptions(true, "h264_nvenc", fps, width, height, openshot::Fraction(1, 1), false, false, 2000000);
            writer.SetAudioOptions(true, "aac", sample_rate, channels, channel_layout, 128000);
            writer.PrepareStreams();
            writer.SetOption(openshot::VIDEO_STREAM, "preset", "p1");
            writer.SetOption(openshot::VIDEO_STREAM, "tune", "ll");
        }

the video is exporting fine however im quite certain its just encoding the video with libx264 like cpu based usage as the time to render is almost exactly the same across various videos that i tried, its not using h264_nvenc 
```

**Comment by teito-dev** [comment]
I think i've found a partial reason for it, however it doesnt fix everything, will get back to you, after ive figured out the problem better
https://github.com/OpenShot/libopenshot/issues/1017#issue-3264796560

**Comment by teito-dev** [comment]
So on initial checking this is happening because for whatever reason, when instantiating multiple FFmpegReaders to load various different clips, its setting up the shared global variables to use CPU decoding , causing the issue

After configuring ffmpeg in libopenshot to be more verbose this is what im getting

```
[2025-07-26 07:06:22.685] [info] Hardware Decoder: 2
[2025-07-26 07:06:22.685] [info] Hardware Decode Device: 0
[2025-07-26 07:06:22.685] [info] Hardware Encode Device: 0
[2025-07-26 07:06:22.685] [info] Special clip type 'intro' found - implementation pending
[h264 @ 0x56479dc98640] Reinit context to 640x368, pix_fmt: yuv420p
Hardware decoding device number: 0
[AVIOContext @ 0x56479dc9f740] Statistics: 227637 bytes read, 0 seeks
[h264 @ 0x56479e6070c0] Reinit context to 640x368, pix_fmt: yuv420p
Hardware decoding device number: 0
[AVIOContext @ 0x56479dcc7d80] Statistics: 227637 bytes read, 0 seeks
[h264 @ 0x56479e395fc0] Reinit context to 640x368, pix_fmt: yuv420p
Hardware decoding device number: 0
[AVIOContext @ 0x56479dcc7d80] Statistics: 227637 bytes read, 0 seeks
[h264 @ 0x56479e395fc0] Reinit context to 640x368, pix_fmt: yuv420p
Hardware decoding device number: 0
[AVIOContext @ 0x56479dcd4d40] Statistics: 227637 bytes read, 0 seeks
[2025-07-26 07:06:23.320] [info] Added video clip: 1af8a2dd-7a04-403d-bd18-d3df38ff317f at position 0 (layer 1)
[2025-07-26 07:06:23.320] [info] Timeline duration: 40 seconds, Total frames: 1200
Encoding Device Nr: 0
[h264_nvenc @ 0x56479dfc6f80] Loaded Nvenc version 13.0
[h264_nvenc @ 0x56479dfc6f80] Nvenc initialized successfully
[2025-07-26 07:06:23.371] [info] Starting export to: output/clipbasic-exported-video.mp4
[2025-07-26 07:06:23.371] [info] Exporting 1200 frames at 30fps (1920x1080)
[h264 @ 0x56479e5a3b00] Reinit context to 640x368, pix_fmt: yuv420p
Hardware decoding device number: 0
[AVIOContext @ 0x56479e5aadc0] Statistics: 227637 bytes read, 0 seeks
[h264 @ 0x56479f4fc100] Reinit context to 640x368, pix_fmt: yuv420p
Hardware decoding device number: 0
[h264 @ 0x56479ef55c40] NVDEC capabilities:
[h264 @ 0x56479ef55c40] format supported: yes, max_mb_count: 65536
[h264 @ 0x56479ef55c40] min_width: 48, max_width: 4096
[h264 @ 0x56479ef55c40] min_height: 16, max_height: 4096
[h264 @ 0x56479ef55c40] Reinit context to 640x368, pix_fmt: cuda
[2025-07-26 07:06:24.214] [info] Export progress: 2.5% (30/1200)
[2025-07-26 07:06:24.863] [info] Export progress: 5.0% (60/1200)
```

As you can see only the last one is pix_fmt:cuda from ffmpeg logs, rest are pix_fmt: yuv420p 
which means its falling back to CPU decoding for a lot of the clips, why ? im not sure yet, need to figure out

This is happening on both VDPAU and CUDA/NVDEC hardware decoders 

Will post back after i figure out the problem, but my hunch is some global variable being shared by ffmpegreader is being overwritten each time
