### ISSUE TITLE
Openshot crashes consistently when applying time->normal->forward->1X then jump to the end of the clip

### ISSUE THREAD

**Issue by fgoudreault** [OpenShot/libopenshot#835]
MWE:
1- open openshot (empty project)
2- import any video (in my case a `.MOV` format)
3- place at beginning and go at the beginning then -> right click -> time -> normal -> forward -> 1X
4- jump to the end of the clip -> Crash consistently

Here is the stack trace:
```
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /home/fgoudreault/Workspace/openshot/libopenshot/build/src/libopenshot.so.21 ( openshot::Clip::get_time_mapped_frame(std::shared_ptr<openshot::Frame>, long)  + 0x103c)  [0x7f8fad1673ac]
  /home/fgoudreault/Workspace/openshot/libopenshot/build/src/libopenshot.so.21 ( openshot::Clip::GetFrame(std::shared_ptr<openshot::Frame>, long, openshot::TimelineInfoStruct*)  + 0xda  )  [0x7f8fad1728ba]
  /home/fgoudreault/Workspace/openshot/libopenshot/build/src/libopenshot.so.21 ( openshot::Timeline::GetOrCreateFrame(std::shared_ptr<openshot::Frame>, openshot::Clip*, long, openshot::TimelineInfoStruct*)  + 0x376 )  [0x7f8fad1ced06]
  /home/fgoudreault/Workspace/openshot/libopenshot/build/src/libopenshot.so.21 ( openshot::Timeline::add_layer(std::shared_ptr<openshot::Frame>, openshot::Clip*, long, bool, float)  + 0xcb  )  [0x7f8fad1cf01b]
  /home/fgoudreault/Workspace/openshot/libopenshot/build/src/libopenshot.so.21 ( openshot::Timeline::GetFrame(long)        + 0x1590)  [0x7f8fad1d3850]
  /home/fgoudreault/Workspace/openshot/libopenshot/build/src/libopenshot.so.21 ( openshot::PlayerPrivate::getFrame()       + 0xaf  )  [0x7f8fad216eff]
  /home/fgoudreault/Workspace/openshot/libopenshot/build/src/libopenshot.so.21 ( openshot::PlayerPrivate::run()            + 0x105 )  [0x7f8fad2170b5]
  /home/fgoudreault/Workspace/openshot/install/libopenshot-audio/lib/libopenshot-audio.so.8 ( juce::Thread::threadEntryPoint()          + 0xd9  )  [0x7f8facfe3359]
  /home/fgoudreault/Workspace/openshot/install/libopenshot-audio/lib/libopenshot-audio.so.8 (                                           + 0x17348d)  [0x7f8facfe348d]
  /lib/x86_64-linux-gnu/libpthread.so.0 (                                           + 0x8609)  [0x7f8fdbd70609]
  /lib/x86_64-linux-gnu/libc.so.6 ( clone                                     + 0x43  )  [0x7f8fdbeaa133]
---- End of Stack Trace ----
```
I just compiled from scratch libopenshot, libopenshot-audio and openshot-qt. I'm using python 3.9 on ubuntu 20.04.

**Comment by JacksonRG** [comment]
I wasn't able to recreate this issue.

@fgoudreault What version of openshot were you using? And could you attach your full log files from when this happened?
They're in `/home/<user_name>/.openshot_qt/`

**Comment by fgoudreault** [comment]
Hi @JacksonRG thanks for your reply. I am using `openshot-qt v2.6.1-dev` and `libopenshot v0.2.7-dev`. Python version `v3.9.5`, qt5 `5.15.2` Here are the logs.

[libopenshot.log](https://github.com/OpenShot/libopenshot/files/9128884/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/libopenshot/files/9128885/openshot-qt.log)

**Comment by JacksonRG** [comment]
Sorry, still looking at this bug, but haven't found anything towards reproducing it.

What operating system (and version) are you using? Also I should have done this first, but [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging) are instructions to enable verbose logging, which might give some more info as to where this crash is happening. Additionally you can run openshot with the `--debug` flag but that will only give extra info on the UI, which doesn't look like its the problem here.
