### ISSUE TITLE
Audio is not playing correctly for some videos

### ISSUE THREAD

**Issue by gofinger** [OpenShot/libopenshot#854]
I would like to point a issue in which audio is not playing correctly in some videos. I am attaching a MP4 video file in which video plays correct but audio is glitchly and sometimes changes completely different. I played this MP4 file in VLC player, it plays correct in it.

https://user-images.githubusercontent.com/115683275/195501141-3a6167e7-c6a2-40a8-82d8-e60cc9ac79e7.mp4

**Comment by Colorjet3** [comment]
You are most likely running OpenShot version 2.6.1-Release-Candidate.  Please go to openshot.org/download/#daily and download the latest DEV Daily Build available (v3.0.0).

Also, if you are running in Windows 10 or Windows 11, In Openshot - Edit | Preference | Preview tab ensure that the Audio Sample Rate is set to 48000 (it probably is set to 44100 right now).

Let us know if this resolved your issue.

**Comment by Colorjet3** [comment]
Hello @gofinger Any update on this?
