### ISSUE TITLE
ffmpeg 4.0 support

### ISSUE THREAD

**Issue by arekm** [OpenShot/libopenshot#87]
ffmpeg 4.0 was released and it drops deprecated AVFMT_RAWPICTURE API. Is #ifdef-ing around it enough in libopenshot?

Ifdefing it and changing:
FF_INPUT_BUFFER_PADDING_SIZE is now AV_INPUT_BUFFER_PADDING_SIZE
CODEC_FLAG_GLOBAL_HEADER is now AV_CODEC_FLAG_GLOBAL_HEADER
is enough to make libopenshot build with ffmpeg 4.0.

**Comment by Bluewind** [comment]
This also blocks ffmpeg 4.0 for Arch Linux. I'd rather not patch libopenshot myself and break things in subtle ways so I'd appreciate a fix from upstream.

**Comment by Bluewind** [comment]
No idea if this is any good, but I don't want to wait any more for a patch that could have come [a year ago](https://www.bountysource.com/issues/41542202-deprecation-warnings-with-ffmpeg) so I'm going ahead and patching this.

[ffmpeg-4.0.patch.txt](https://github.com/OpenShot/libopenshot/files/1984714/ffmpeg-4.0.patch.txt)

**Comment by ArchangeGabriel** [comment]
You could have linked here directly: https://github.com/OpenShot/libopenshot/issues/49 ;)

**Comment by peanutbutterandcrackers** [comment]
Hey there!

@Bluewind - I see that you have done some work regarding this. Perhaps you'd like to actually submit a PR, good sir? That way, you'd get comments and code reviews on your patch, and maybe it'll even be merged into the main code base!
OpenShot needs more talented developers like you who are willing to volunteer for this Open Source project. I hope you'll consider submitting a PR, and that you'll stick around and keep on supporting OpenShot!

**Comment by peanutbutterandcrackers** [comment]
@arekm - Good sir, perhaps you might also want to submit a PR? This project could really use talented programmers like you.

**Comment by ferdnyc** [comment]
FFmpeg support is long since integrated.
