### ISSUE TITLE
Bug Fix: Alpha Mask / Wipe Transition

### ISSUE THREAD

**Issue by xotmatrix** [OpenShot/libopenshot#873]
I'd only started using OpenShot today but it soon become clear that the wipe transitions were not performing correctly. I believe eight or more years ago, when ImageMagick dependencies were removed from OpenShot, the reimplementer of this feature got the order of operations mixed up. Having built such a system myself, I recognized this sort of error. However, being unfamiliar with OpenShot and unable to build it for myself, I can only hope that I have correctly located the source of the problem.

![OpenSpot_Mask cpp_regression](https://user-images.githubusercontent.com/14209329/202600019-3d64fa57-aced-426b-bb3f-762241d643f6.jpg)

This video demonstrates the problem. The first two transitions were rendered with OpenShot using the `clock_right_to_left` mask. The first is set to the default 3.0 contrast value. The second is set to very high contrast to show that the wipe does not actually progress. The next two transitions implement OpenShot's code in a shader with some small corrections. The wipe progresses as expected.

https://www.youtube.com/watch?v=rdR2LbTWA-o

I'm sorry I can't build this project and submit a proper pull request but I can show you how to fix it in a way that performs correctly. It looks virtually the same for the default 3.0 contrast value. At maximum contrast 20.0 the wipe edge is sharp.

https://github.com/OpenShot/libopenshot/blob/7617e9165e67ef68525aa9cc247dd54bd384c724/src/effects/Mask.cpp#L113-L124

```
    // Adjust the brightness
    gray_value += (255 * brightness_value);
    
    // Adjust the contrast
    float factor = (20 / (20 - contrast_value));
    gray_value = (factor * (gray_value - 128) + 128);
    
    // Calculate the % change in alpha
    float alpha_percent = float(constrain(A - gray_value)) / 255.0;
```

This HTML5/WebGL demonstration shows the corrected code in operation with several OpenShot alpha masks. It can be interacted with in a variety of ways.

https://xotmatrix.github.io/demos/gradient-mask-transition/

Note: Some of the alpha mask images in [openshot-qt](https://github.com/OpenShot/openshot-qt)/[src](https://github.com/OpenShot/openshot-qt/tree/develop/src)/[transitions](https://github.com/OpenShot/openshot-qt/tree/develop/src/transitions)/extra/ are low-resolution and heavily compressed and should be remastered to look their best.

**Comment by jonoomph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Transition / Wipe Regression](https://trello.com/c/stb0c4Sq/214-transition-wipe-regression)

**Comment by jonoomph** [comment]
Thanks @xotmatrix! Good catch! This works well, except for values 20.0 and above, which makes the image completely transparent (I think)... haven't dug into this very deeply yet.

**Comment by jonoomph** [comment]
Ahhh, found it. `20.0` causes a divide by error / infinity error. I'll add a small constraint around this to prevent it.

**Comment by xotmatrix** [comment]
Oh, of course. I should have seen that. Glad it works. 👍
