### ISSUE TITLE
NVENC: Error while writing raw video frame

### ISSUE THREAD

**Issue by tildeman** [OpenShot/libopenshot#890]
The issue occurs when using the NVENC options when exporting the video (in openshot-qt).
Everything reads and writes fine until frame 33 where FFmpeg unexpectedly returns -22 (Invalid argument)
The export works fine on every other option (with CPU or VAAPI)
This probably has to do with `av_packet_rescale_ts` on line 2270 of FFmpegWriter.cpp, it might be wrong (although I can't easily use a C++ debugger on a Python script that is openshot-qt)

OS: Gentoo Linux x86_64
RAM: 16GB
CPU: Intel i7-8750H (12) @ 4.100GHz 
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630]
GPU: NVIDIA GeForce GTX 1050 Ti Mobile
libopenshot: 0.3.0 (built from upstream using a custom package manager overlay)
nVidia drivers: 525.60.13
FFmpeg: 4.4.3

Here's a log file for reference: [libopenshot.log](https://github.com/OpenShot/libopenshot/files/10298826/libopenshot.log)
This issue is probably equivalent to the one on https://github.com/OpenShot/openshot-qt/issues/4086

**Comment by jonoomph** [comment]
If possible, can you try running this in GDB:

```
# From Source
cd openshot-qt
gdb python3
(gdb) run src/launch.py --debug
```

OR

```
# From Package / or AppImage
gdb openshot-qt          OR        gdb openshot*.AppImage
(gdb) run --debug
```

**Comment by jonoomph** [comment]
Also, I would be curious to know your export settings (format, video codec, audio codec, bit rates, etc...). Thx

**Comment by aliedperezmartinez** [comment]
Hi, I can reproduce it too. This is the relevant log from the terminal:

> Encoding Device Nr: 1
[h264_nvenc @ 0x53e5300] [Eval @ 0x7ffc743ca660] Undefined constant or missing '(' in 'zerolatency'
[h264_nvenc @ 0x53e5300] Unable to parse option value "zerolatency"
Hardware decoding device number: 1
Hardware decoding device number: 1
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3055, resource id: 12018999, major code: 40 (TranslateCoords), minor code: 0
[mp4 @ 0x5a54580] pts (0) < dts (16384) in stream 0
[mp4 @ 0x5a54580] pts (512) < dts (16384) in stream 0
[mp4 @ 0x5a54580] pts (1024) < dts (16384) in stream 0
[mp4 @ 0x5a54580] pts (1536) < dts (16384) in stream 0
[mp4 @ 0x5a54580] pts (2048) < dts (16384) in stream 0
[mp4 @ 0x5a54580] pts (2560) < dts (16384) in stream 0
[mp4 @ 0x5a54580] pts (3072) < dts (16384) in stream 0
[mp4 @ 0x5a54580] pts (3584) < dts (16384) in stream 0
INFO export: Error type string: Error while writing raw video frame

This is the setting I can reproduce the error with:
![Screenshot_2023-02-25_17-48-42](https://user-images.githubusercontent.com/80164584/221372207-f602e51d-8e72-49b7-8bb5-85473c56de8d.png)

mkv crashes too

**Comment by aliedperezmartinez** [comment]
Openshot version: 3.0.0
libopenshot version: 0.3.0

```
alied@development:~$ uname -a
Linux development 6.2.1 #1 SMP Sat Feb 25 12:08:49 GMT 2023 x86_64 GNU/Linux
alied@development:~$ cat /etc/debian_version 
bookworm/sid
```

**Comment by aperture147** [comment]
Hi, I'm also facing the same error with `pyopenshot`. Please check #956 for more insight.

**Comment by Colorjet3** [comment]
Hardware acceleration in general is broken/not well supported.  This bug is documented and in the queue to be fixed.  No ETA at this time.

**Comment by rajeevrk** [comment]
Also seeing the same issue still on the following config :

OS: Fedora Linux 40 (Workstation Edition) x86_64
RAM: 40GB
CPU: Intel i9-11900H (16) @ 2.500GHz
GPU1: Intel® UHD Graphics (TGL GT1)
GPU2: NVIDIA GeForce RTX™ 3060 Laptop GPU
libopenshot: 0.3.0 (built from upstream using a custom package manager overlay)
nVidia drivers: 560.35.03-3
FFmpeg: 6.1.2 built with gcc 14 (GCC)
openshot-qt version: 3.2.1
libopenshot version: 0.3.3
platform: Linux-6.10.8-200.fc40.x86_64-x86_64-with-glibc2.39
python version: 3.12.5
qt5 version: 5.15.14
pyqt5 version: 5.15.10

Relevant Error message from the Openshot output, while trying to render projects via NVENC :

Encoding Device Nr: 0
INFO export: Error type string: Error while writing raw video frame
INFO main_window: Export Video add cancelled

I am able to perform custom debug builds, if needed of both openshot and ffmpeg, so am happy to assist in debugging, under the guidance of any experienced openshot devs.
