### ISSUE TITLE
Frame copy constructor does not preserve sample rate

### ISSUE THREAD

**Issue by scott--** [OpenShot/libopenshot#9]
I have been trying to use libopenshot as an FFmpeg wrapper, to annotate a video with drawings from opencv. The benefit is that libopenshot can preserve audio, while opencv's video reader discards the audio. I like the libopenshot API, and the code below seems to work. However, I have run into these two confusing issues:
- There is no frame constructor that sets the sample rate, not even the copy constructor, or Frame::DeepCopy, which was very confusing. The comments within Frame.h are actually incorrect in the usage of the constructor. 
- I was using an input video of 1920x1080 and an output of 1080x1080. Calling
  f = r.GetFrame(...); w.WriteFrame(f); actually works, but scales the image. However, calling f = r.GetFrame(...); f->AddImage(1080, 1080 ...); w.WriteFrame(f); causes a segfault, even though f should now be the correct size?

``` c++

  cv::Mat cropped_frame, frame_out;
  FFmpegReader r("input.mp4");
  r.Open();

  // Get frame that requires a seek
  tr1::shared_ptr<Frame> f = r.GetFrame(1);

  FFmpegWriter w("output.mkv");
  w.SetVideoOptions(true, "libx264", r.info.fps, 1080, 1080, Fraction(1,1), false, false, r.info.video_bit_rate);
  w.SetAudioOptions(true, "libfaac", r.info.sample_rate, 2, LAYOUT_STEREO, r.info.audio_bit_rate);
  w.PrepareStreams();
  w.WriteHeader();
  w.Open();

  for (unsigned long count = 1; count < 30000; count++)
  {
     time = ((long double) count )/30.0;
     f = r.GetFrame(count);


     int width = f->GetWidth();
     int height = f->GetHeight();
     uint8_t * data = (uint8_t*) f->GetPixels();

     cv::Mat frame(height,
       width,
       CV_8UC4,
       data);

     cv::Rect roi(0, 0, 1080, 1080);
     cropped_frame = frame(roi);
     cv::transpose(cropped_frame, frame_out);
     cv::flip(frame_out, frame_out,0);
     cv::rectangle(frame, my_rect, my_color, -1);

     tr1::shared_ptr<Frame> out_f(new Frame(f->number, // Frame number
            frame_out.size().width,  // Width of image
            frame_out.size().height, // Height of image
            "#000000" )); // color

     out_f->ResizeAudio(f->GetAudioChannelsCount(), f->GetAudioSamplesCount(),
     f->SampleRate(), f->ChannelsLayout());
     out_f->AddAudio(false, 0, 0, f->GetAudioSamples(0), f->GetAudioSamplesCount(), 1.0);
     out_f->AddAudio(false, 1, 0, f->GetAudioSamples(1), f->GetAudioSamplesCount(), 1.0);
     out_f->AddImage(frame_out.size().width, frame_out.size().height, 4, QImage::Format_ARGB32, frame_out.data);
     w.WriteFrame(out_f);
  }

  w.WriteTrailer();
  w.Close();
  r.Close();
```

**Comment by ferdnyc** [comment]
Honestly I'm not even sure if this is still an issue, but given the age I think it's best if it be closed, and a new report filed against the current 0.2.3 code if the issue is still present.
