### ISSUE TITLE
While editing,  audio and video get out of sync

### ISSUE THREAD

**Issue by dengert** [OpenShot/libopenshot#906]
While editing, video and audio get out of sync with audio falling further behind as time goes on making it all but impossible  to splice based on audio clues.  

Version 3.0.0 
Windows 11
12th Gen Intel(R) Core(TM) i5-12600K   3.69 GHz using built in intel graphics. 
Input Mp4  files created using LG Velvet phone. 1280/720 11958kbs12114kps 29.92 f/s Audio 155kbs 48.000 kHz

The [I5-12600K](https://ark.intel.com/content/www/us/en/ark/products/134589/intel-core-i512600k-processor-20m-cache-up-to-4-90-ghz.html)  has 6 fast high power processors, and 4 slow low processors for total of 16 threads.  Problem may be related to which processors are used for video and which for audio. 

The previous version 2  had similar problem, audio was fine, but video was choppy. 

Version 2 on older Windows 10 with Intel I5 gen 3 did not have sync problems.  

The exported video "MP4 (h.264 qsv) Med"  in both v2 and v3 do not have problems.  Just will trying to edit.

**Comment by dengert** [comment]
The problem does not appear related to CPU or windows version. Installing the same 3.0.0 version of OpenShot on Windows 10 with older CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz   3.40 GHz OS:  Windows 10 Pro 22H2
shows the same problem of audio and video is out of sync while editing.

**Comment by Colorjet3** [comment]
Hello @dengert.  v3.0.0-Release-Candidate exhibited this symptom on some Windows installations (10 & 11).  Please do this:

1.  Close Openshot.
2.  Go to openshot.org/download/#daily and get the latest DEV Daily Build available.
3.  Make a backup of c:\users\username\.openshot_qt folder.
4.  Delete c:\users\username\.openshot_qt folder.
5.  Install the latest DEV Daily Build.
6.  Start Openshot.
7.  Go to Edit | Preferences | Preview tab and ensure that the Default Audio Sample Rate is set to 48000.  If not, change it to this and restart Openshot.
8.  Open your project and confirm that the audio/video sync issue has been resolved.

**Comment by dengert** [comment]
With build from 2022-12-08   Default Audio Sample Rate was 44100.

.openshot-qt shows  this 7 times:
```
06:23:18 INFO preview_thread: Detected default audio device sample rate: 48000
06:23:18 WARNING preview_thread: Your sample rate (48000) does not match OpenShot (44100). This can potentially play audio too fast/slow if not fixed. Adjust your 'Preferences->Preview->Default Sample Rate to match your system rate: 48000, and restart OpenShot.
```

When changed to 48000 things are in sync, also in sync with  daily-11058    2023-02-15 22.55

**Comment by Colorjet3** [comment]
Hello @dengert. Glad it is all working for you.  Best of luck with your projects.
