### ISSUE TITLE
Where is the main() function or the program entry?

### ISSUE THREAD

**Issue by longluo** [OpenShot/libopenshot#940]
Every program has a `main()` function as the program entry，but I use 

```bash
grep -rn "main" *.*
```

I found nothing, so where is the program entry and the main loop of the openShot? 

Thank you very much.

**Comment by mlell** [comment]
Hi,
as far as I know, OpenShot is actually a python program which uses `libopenshot` as a compiled module ([see this tutorial on Python Extension Modules](https://realpython.com/build-python-c-extension-module/), if necessary). So you will not find a main() function here. 

Go to the repository openshot-qt, file [src/launch.py](https://github.com/OpenShot/openshot-qt/blob/develop/src/launch.py). That is where this program starts. It will include the code in this repo with the line `import openshot`

**Comment by longluo** [comment]
> Hi, as far as I know, OpenShot is actually a python program which uses `libopenshot` as a compiled module ([see this tutorial on Python Extension Modules](https://realpython.com/build-python-c-extension-module/), if necessary). So you will not find a main() function here.
> 
> Go to the repository openshot-qt, file [src/launch.py](https://github.com/OpenShot/openshot-qt/blob/develop/src/launch.py). That is where this program starts. It will include the code in this repo with the line `import openshot`

Thx very much.
