### ISSUE TITLE
[development] Can you provide an example of using python to implement transitions and special effects?

### ISSUE THREAD

**Issue by 625781186** [OpenShot/libopenshot#952]
Can you provide an example of using python to implement transitions and special effects?

Thanks .

**Comment by jonoomph** [comment]
We do not have any current examples in Python to add transitions and special effects, however you are always welcome to look at our source code, and [follow this guide](https://github.com/OpenShot/openshot-qt/wiki/Become-a-Developer) to get things running locally. Another approach is to create some simple test projects (*.osp), and inspect the JSON inside these files. JSON is very simple to generate in most programming languages, and that might allow you to script lots of interesting templates and project automation. Good luck!
